import React,{useEffect,useRef,useState} from 'react'
import {Link} from 'react-router'
import {useTranslation} from 'react-i18next'
import {createRule,acceptRule,deleteRule} from '../../lib/thesis-api'
import {STRESS_BASES} from '../../../../supabase/functions/_shared/intel/stress-scenario-contract'
import {useMarketResearch} from '../../lib/useMarketResearch'
import {venueConditionChoices} from '../../../../supabase/functions/_shared/intel/venue-condition-sources'
const periods={3600:'1h',86400:'24h',604800:'7d'}
export default function ThesisConditions(props){return <Conditions key={`${props.userId}:${props.thesis.org_id}:${props.thesis.id}`} {...props}/>}
function Conditions({supabase,userId,thesis,editable,onChanged}){
 const {t}=useTranslation('intel',{useSuspense:false})
 const [form,setForm]=useState({description:'',basis:'price',kind:'invalidation',comparator:'lte',threshold:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null),alive=useRef(true),operation=useRef(null)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 const venue=useMarketResearch('venueContext',{canonicalKey:thesis.subject_canonical_key,refresh:false},editable&&form.basis==='venue')
 const sources=venue.result?.schemaVersion===1?venueConditionChoices([...(venue.result.derivatives?.observations||[]),...(venue.result.cmcContract?.observations||[])],venue.result.depth,Date.parse(venue.result.evaluatedAt)):[],source=sources.find(s=>s.key===form.source)
 const run=async action=>{setBusy(true);setError(null);try{await action();if(alive.current)await onChanged()}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 const save=event=>{event.preventDefault();const threshold=Number(form.threshold);if(form.threshold.trim()===''||!Number.isFinite(threshold)){setError(t('journal.conditions.threshold_invalid',{defaultValue:'Enter a finite numeric threshold. Zero is valid.'}));return}const basis=form.basis==='venue'?source:STRESS_BASES[form.basis];if(!basis){setError(t('journal.conditions.source_required',{defaultValue:'Choose a compatible recorded source before saving.'}));return}const body={description:form.description,rule_kind:form.kind,metric:basis.metric,comparator:form.comparator,threshold,threshold_unit:basis.unit,time_window:periods[basis.periodSeconds]||(basis.periodSeconds?`${basis.periodSeconds}s`:'current'),source_metric:basis.sourceMetric||basis.metric,status:'proposed',visibility:'private'};const signature=JSON.stringify(body);if(operation.current?.signature!==signature)operation.current={signature,id:crypto.randomUUID()};run(async()=>{await createRule(supabase,thesis.org_id,userId,thesis.id,{...body,id:operation.current.id});if(alive.current){operation.current=null;setForm(previous=>({...previous,description:'',threshold:''}))}})}
 return <section className="space-y-4" aria-label={t('journal.conditions.section_label',{defaultValue:'Structured thesis conditions'})}>
  <p>{t('journal.conditions.intro',{defaultValue:'Testable confirmation and invalidation conditions use fresh retained evidence. Activation is explicit and fires once before pausing. A matching condition requests your review; it does not change your thesis conclusion.'})}</p>
  {editable&&<form onSubmit={save} className="space-y-3 border-y border-[var(--border-default)] py-3"><label className="block">{t('journal.conditions.description_label',{defaultValue:'Condition in your words'})}<input required maxLength={500} className="input w-full" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="flex flex-wrap gap-3">
   <label>{t('journal.conditions.purpose',{defaultValue:'Purpose'})}<select className="select" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="invalidation">{t('journal.conditions.kinds.invalidation',{defaultValue:'Invalidation'})}</option><option value="confirmation">{t('journal.conditions.kinds.confirmation',{defaultValue:'Confirmation'})}</option></select></label>
   <label>{t('journal.conditions.metric_period',{defaultValue:'Metric and period'})}<select className="select" value={form.basis} onChange={e=>setForm({...form,basis:e.target.value,source:''})}>{Object.entries(STRESS_BASES).map(([key,basis])=><option key={key} value={key}>{t(`journal.conditions.bases.${key}`,{defaultValue:basis.label})}</option>)}<option value="venue">{t('journal.conditions.venue_source',{defaultValue:'Recorded venue / on-chain source'})}</option></select></label>
   <label>{t('journal.conditions.comparison',{defaultValue:'Comparison'})}<select className="select" value={form.comparator} onChange={e=>setForm({...form,comparator:e.target.value})}><option value="lt">{t('journal.conditions.comparators.lt',{defaultValue:'Less than'})}</option><option value="lte">{t('journal.conditions.comparators.lte',{defaultValue:'At or below'})}</option><option value="gt">{t('journal.conditions.comparators.gt',{defaultValue:'Greater than'})}</option><option value="gte">{t('journal.conditions.comparators.gte',{defaultValue:'At or above'})}</option></select></label>
   <label>{t('journal.conditions.threshold',{defaultValue:'Threshold'})}<input className="input" type="number" step="any" required value={form.threshold} onChange={e=>setForm({...form,threshold:e.target.value})}/></label><button className="btn" disabled={busy}>{t('journal.conditions.save_proposed',{defaultValue:'Save proposed condition'})}</button>
  </div>{form.basis==='venue'&&<div className="space-y-2">{venue.loading?<p role="status">{t('journal.conditions.reading_sources',{defaultValue:'Reading retained source observations…'})}</p>:venue.error?<p role="alert">{venue.error}</p>:<label className="block">{t('journal.conditions.exact_source',{defaultValue:'Exact source'})}<select className="select w-full" value={form.source||''} onChange={e=>setForm({...form,source:e.target.value})}><option value="">{t('journal.conditions.choose_source',{defaultValue:'Choose a recorded market or contract source'})}</option>{sources.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></label>}{source&&<p>{source.observation.value} {source.unit} · {t('journal.conditions.observed_at',{date:source.observation.observedAt,defaultValue:'observed {{date}}'})} · {t('journal.conditions.known_at',{date:source.observation.recordedAt,defaultValue:'known {{date}}'})}</p>}<p className="intel-analysis-caption">{t('journal.conditions.source_caveats',{defaultValue:'CMC holder counts use daily account observations. Pool activity tests the latest reported event, not net flows or your trades. Open interest stays contract-specific. Funding requires a confirmed unit and interval. Asset liquidation totals are not assigned to venues. Depth needs a recorded known-at time and represents the best level only.'})}</p><button type="button" className="intel-text-link" disabled={venue.loading} onClick={venue.refresh}>{t('journal.conditions.reload_sources',{defaultValue:'Reload retained sources'})}</button> · <Link className="intel-text-link" to={`/intel/asset/${encodeURIComponent(thesis.subject_canonical_key)}#asset-venue-evidence`}>{t('journal.conditions.open_venue_evidence',{defaultValue:'Open asset venue evidence'})}</Link>{!venue.loading&&!venue.error&&!sources.length&&<p>{t('journal.conditions.no_fresh_source',{defaultValue:'No compatible fresh source is available. Refresh shared evidence from the asset workspace if needed.'})}</p>}</div>}<p className="intel-analysis-caption">{t('journal.conditions.saved_with_words',{defaultValue:'The selected unit, source and observation period are saved with your words. Missing compatible source coverage remains unavailable. No provider refresh or AI call is made here.'})}</p></form>}
  {error&&<p role="alert">{error}</p>}
  {(thesis.rules||[]).length===0?<p>{t('journal.conditions.none_recorded',{defaultValue:'No confirmation or invalidation conditions recorded.'})}</p>:(thesis.rules||[]).map(rule=><article key={rule.id} className="border-b border-[var(--border-default)] py-3 space-y-2"><div className="flex flex-wrap justify-between gap-2"><h3>{rule.description}</h3><span>{rule.rule_kind} · {rule.status}</span></div><p>{rule.metric} {rule.comparator} {rule.threshold??'—'} {rule.threshold_unit||t('journal.conditions.unit_not_recorded',{defaultValue:'unit not recorded'})} · {rule.time_window||t('journal.conditions.period_not_recorded',{defaultValue:'period not recorded'})}</p>
   {/^(venue|depth|liquidation|contract):/.test(rule.source_metric||'')&&<p className="intel-analysis-caption">{t('journal.conditions.recorded_source',{defaultValue:'Recorded source'})}: {rule.source_metric}</p>}{rule.evaluation_state?.status&&<p>{rule.evaluation_state.status.replaceAll('_',' ')} · {new Date(rule.evaluation_state.checkedAt).toLocaleString()}{rule.evaluation_state.reason?` · ${rule.evaluation_state.reason}`:''}</p>}
   {rule.evaluation_state?.evidence_version&&<details><summary>{t('journal.conditions.original_evidence',{defaultValue:'Original evaluation evidence'})}</summary><p className="break-all">{t('journal.conditions.version',{defaultValue:'Version'})} {rule.evaluation_state.evidence_version}</p><p>{t('journal.conditions.source_observed_at',{date:rule.evaluation_state.observation?.observedAt||t('journal.conditions.not_available',{defaultValue:'not available'}),defaultValue:'Source observed {{date}}'})} · {t('journal.conditions.known_at',{date:rule.evaluation_state.observation?.recordedAt||t('journal.conditions.not_available',{defaultValue:'not available'}),defaultValue:'known {{date}}'})}</p><p className="break-all">{rule.evaluation_state.observation?.sourceRef}</p>{(rule.evaluation_state.observation?.sourceMetric||/^(venue|depth|liquidation|contract):/.test(rule.evaluation_state.condition?.source_metric||''))&&<p className="break-all">{t('journal.conditions.matched_source',{defaultValue:'Matched source'})}: {rule.evaluation_state.observation?.sourceMetric||t('journal.conditions.not_recorded_in_receipt',{defaultValue:'Not recorded in this receipt'})}</p>}</details>}
   {editable&&<div className="flex flex-wrap gap-3">{rule.status!=='active'&&<button className="btn" disabled={busy||!rule.threshold_unit||!rule.time_window||rule.threshold==null} onClick={()=>run(()=>acceptRule(supabase,thesis.org_id,rule.id))}>{t('journal.conditions.activate_once',{defaultValue:'Activate once'})}</button>}<button className="intel-text-link" disabled={busy} onClick={()=>run(()=>deleteRule(supabase,rule.id))}>{t('journal.conditions.delete_condition',{defaultValue:'Delete condition'})}</button>{rule.alert_rule_id&&<Link className="intel-text-link" to="/intel/alerts">{t('journal.conditions.alert_history',{defaultValue:'Alert history and delivery'})}</Link>}</div>}
  </article>)}
 </section>
}
