import React,{useEffect,useRef,useState} from 'react'
import {Link} from 'react-router'
import {createRule,acceptRule,deleteRule} from '../../lib/thesis-api'
import {STRESS_BASES} from '../../../../supabase/functions/_shared/intel/stress-scenario-contract'
import {useMarketResearch} from '../../lib/useMarketResearch'
import {venueConditionChoices} from '../../../../supabase/functions/_shared/intel/venue-condition-sources'
const periods={3600:'1h',86400:'24h',604800:'7d'}
export default function ThesisConditions(props){return <Conditions key={`${props.userId}:${props.thesis.org_id}:${props.thesis.id}`} {...props}/>}
function Conditions({supabase,userId,thesis,editable,onChanged}){
 const [form,setForm]=useState({description:'',basis:'price',kind:'invalidation',comparator:'lte',threshold:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null),alive=useRef(true),operation=useRef(null)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 const venue=useMarketResearch('venueContext',{canonicalKey:thesis.subject_canonical_key,refresh:false},editable&&form.basis==='venue')
 const sources=venue.result?.schemaVersion===1?venueConditionChoices([...(venue.result.derivatives?.observations||[]),...(venue.result.cmcContract?.observations||[])],venue.result.depth,Date.parse(venue.result.evaluatedAt)):[],source=sources.find(s=>s.key===form.source)
 const run=async action=>{setBusy(true);setError(null);try{await action();if(alive.current)await onChanged()}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 const save=event=>{event.preventDefault();const threshold=Number(form.threshold);if(form.threshold.trim()===''||!Number.isFinite(threshold)){setError('Enter a finite numeric threshold. Zero is valid.');return}const basis=form.basis==='venue'?source:STRESS_BASES[form.basis];if(!basis){setError('Choose a compatible recorded source before saving.');return}const body={description:form.description,rule_kind:form.kind,metric:basis.metric,comparator:form.comparator,threshold,threshold_unit:basis.unit,time_window:periods[basis.periodSeconds]||(basis.periodSeconds?`${basis.periodSeconds}s`:'current'),source_metric:basis.sourceMetric||basis.metric,status:'proposed',visibility:'private'};const signature=JSON.stringify(body);if(operation.current?.signature!==signature)operation.current={signature,id:crypto.randomUUID()};run(async()=>{await createRule(supabase,thesis.org_id,userId,thesis.id,{...body,id:operation.current.id});if(alive.current){operation.current=null;setForm(previous=>({...previous,description:'',threshold:''}))}})}
 return <section className="space-y-4" aria-label="Structured thesis conditions">
  <p>Testable confirmation and invalidation conditions use fresh retained evidence. Activation is explicit and fires once before pausing. A matching condition requests your review; it does not change your thesis conclusion.</p>
  {editable&&<form onSubmit={save} className="space-y-3 border-y border-[var(--border-default)] py-3"><label className="block">Condition in your words<input required maxLength={500} className="input w-full" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="flex flex-wrap gap-3">
   <label>Purpose<select className="select" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="invalidation">Invalidation</option><option value="confirmation">Confirmation</option></select></label>
   <label>Metric and period<select className="select" value={form.basis} onChange={e=>setForm({...form,basis:e.target.value,source:''})}>{Object.entries(STRESS_BASES).map(([key,basis])=><option key={key} value={key}>{basis.label}</option>)}<option value="venue">Recorded venue / on-chain source</option></select></label>
   <label>Comparison<select className="select" value={form.comparator} onChange={e=>setForm({...form,comparator:e.target.value})}><option value="lt">Less than</option><option value="lte">At or below</option><option value="gt">Greater than</option><option value="gte">At or above</option></select></label>
   <label>Threshold<input className="input" type="number" step="any" required value={form.threshold} onChange={e=>setForm({...form,threshold:e.target.value})}/></label><button className="btn" disabled={busy}>Save proposed condition</button>
  </div>{form.basis==='venue'&&<div className="space-y-2">{venue.loading?<p role="status">Reading retained source observations…</p>:venue.error?<p role="alert">{venue.error}</p>:<label className="block">Exact source<select className="select w-full" value={form.source||''} onChange={e=>setForm({...form,source:e.target.value})}><option value="">Choose a recorded market or contract source</option>{sources.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></label>}{source&&<p>{source.observation.value} {source.unit} · observed {source.observation.observedAt} · known {source.observation.recordedAt}</p>}<p className="intel-analysis-caption">CMC holder counts use daily account observations. Pool activity tests the latest reported event, not net flows or your trades. Open interest stays contract-specific. Funding requires a confirmed unit and interval. Asset liquidation totals are not assigned to venues. Depth needs a recorded known-at time and represents the best level only.</p><button type="button" className="intel-text-link" disabled={venue.loading} onClick={venue.refresh}>Reload retained sources</button> · <Link className="intel-text-link" to={`/intel/asset/${encodeURIComponent(thesis.subject_canonical_key)}#asset-venue-evidence`}>Open asset venue evidence</Link>{!venue.loading&&!venue.error&&!sources.length&&<p>No compatible fresh source is available. Refresh shared evidence from the asset workspace if needed.</p>}</div>}<p className="intel-analysis-caption">The selected unit, source and observation period are saved with your words. Missing compatible source coverage remains unavailable. No provider refresh or AI call is made here.</p></form>}
  {error&&<p role="alert">{error}</p>}
  {(thesis.rules||[]).length===0?<p>No confirmation or invalidation conditions recorded.</p>:(thesis.rules||[]).map(rule=><article key={rule.id} className="border-b border-[var(--border-default)] py-3 space-y-2"><div className="flex flex-wrap justify-between gap-2"><h3>{rule.description}</h3><span>{rule.rule_kind} · {rule.status}</span></div><p>{rule.metric} {rule.comparator} {rule.threshold??'—'} {rule.threshold_unit||'unit not recorded'} · {rule.time_window||'period not recorded'}</p>
   {/^(venue|depth|liquidation|contract):/.test(rule.source_metric||'')&&<p className="intel-analysis-caption">Recorded source: {rule.source_metric}</p>}{rule.evaluation_state?.status&&<p>{rule.evaluation_state.status.replaceAll('_',' ')} · {new Date(rule.evaluation_state.checkedAt).toLocaleString()}{rule.evaluation_state.reason?` · ${rule.evaluation_state.reason}`:''}</p>}
   {rule.evaluation_state?.evidence_version&&<details><summary>Original evaluation evidence</summary><p className="break-all">Version {rule.evaluation_state.evidence_version}</p><p>Source observed {rule.evaluation_state.observation?.observedAt||'not available'} · known {rule.evaluation_state.observation?.recordedAt||'not available'}</p><p className="break-all">{rule.evaluation_state.observation?.sourceRef}</p>{(rule.evaluation_state.observation?.sourceMetric||/^(venue|depth|liquidation|contract):/.test(rule.evaluation_state.condition?.source_metric||''))&&<p className="break-all">Matched source: {rule.evaluation_state.observation?.sourceMetric||'Not recorded in this receipt'}</p>}</details>}
   {editable&&<div className="flex flex-wrap gap-3">{rule.status!=='active'&&<button className="btn" disabled={busy||!rule.threshold_unit||!rule.time_window||rule.threshold==null} onClick={()=>run(()=>acceptRule(supabase,thesis.org_id,rule.id))}>Activate once</button>}<button className="intel-text-link" disabled={busy} onClick={()=>run(()=>deleteRule(supabase,rule.id))}>Delete condition</button>{rule.alert_rule_id&&<Link className="intel-text-link" to="/intel/alerts">Alert history and delivery</Link>}</div>}
  </article>)}
 </section>
}
