import React,{useEffect,useId,useRef,useState} from 'react'
import {Link} from 'react-router'
import {readPerformanceLedger,savePerformanceReview,readPerformanceHistory} from '../../lib/performance-api'
const date=value=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'long'}):'Not recorded'
const local=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19)}
const human=value=>(value||'unreviewed').replaceAll('_',' ')
export default function ThesisPerformanceLedger(props){return <Ledger key={`${props.orgId}:${props.userId}`} {...props}/>}
function Ledger({supabase,orgId,userId}){
 const [data,setData]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState(false),[editing,setEditing]=useState(null),[history,setHistory]=useState(null),alive=useRef(true)
 const load=async(cursor=null)=>{setBusy(true);setError(null);try{const result=await readPerformanceLedger(supabase,orgId,cursor);if(alive.current)setData(old=>cursor?{...result,rows:[...(old?.rows||[]),...result.rows.filter(row=>!old?.rows.some(previous=>previous.id===row.id))]}:result)}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 useEffect(()=>{alive.current=true;if(orgId&&userId)load();return()=>{alive.current=false}},[orgId,userId,supabase])
 const showHistory=async(row,page=0)=>{setBusy(true);setError(null);try{const result=await readPerformanceHistory(supabase,orgId,userId,row.id,page);if(alive.current)setHistory({row,...result})}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 return <section aria-label="Private thesis performance ledger" className="space-y-3">
  <div className="flex flex-wrap justify-between items-center gap-3"><h2>Private thesis performance ledger</h2><button className="intel-text-link" disabled={busy} onClick={()=>load()}>Refresh ledger</button></div>
  <p className="intel-analysis-caption">Original forecasts and later assessments. These are your recorded research judgments; realized portfolio and journal P&L remain separate below.</p>
  {error&&<><p role="alert">{error}</p><button className="btn" onClick={()=>load()}>Retry ledger</button></>}{busy&&<p role="status">Loading performance records…</p>}
  {data&&<><p>{data.summary.total} owned theses · {Object.entries(data.summary.assessments).map(([key,count])=>`${count} ${human(key)}`).join(' · ')}</p><p className="intel-analysis-caption">{data.basis}</p>
   {data.rows.length===0?<p>No theses recorded in this workspace.</p>:<div className="overflow-x-auto"><table className="w-full text-sm" style={{minWidth:720}}><caption className="sr-only">All private thesis assessments, including unresolved outcomes</caption><thead><tr className="text-left border-b border-[var(--border-default)]"><th>Thesis</th><th>Original decision</th><th>Latest assessment</th><th>Review window</th><th>Actions</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id} className="border-b border-[var(--border-default)] align-top"><td className="py-3 pr-4 max-w-xs"><Link className="intel-text-link" to={`/intel/theses/${row.id}`}>{row.title}</Link><p className="text-xs break-all">{row.subject_canonical_key||'Identity not recorded'} · {row.status}</p></td><td className="py-3 pr-4"><time>{date(row.original_forecast?.occurred_at)}</time>{row.original_forecast?<details><summary>Original words</summary><OriginalForecast record={row.original_forecast}/></details>:<p>Original words unavailable. Current text is not substituted.</p>}</td><td className="py-3 pr-4">{human(row.latest_review?.evaluation.assessment)}{row.latest_review&&<p className="text-xs">Recorded {date(row.latest_review.recorded_at)}</p>}</td><td className="py-3 pr-4">{row.latest_review?<><time>{date(row.latest_review.evaluation.from)}</time><br/><time>{date(row.latest_review.evaluation.to)}</time><p className="text-xs">{row.latest_review.evaluation.retrospective_window?'Window declared after it began':'Window declared before it began'}</p></>:'No window declared'}</td><td className="py-3"><button className="intel-text-link" onClick={()=>setEditing(row)}>Record assessment</button><br/><button className="intel-text-link" disabled={busy} onClick={()=>showHistory(row)}>Assessment history</button></td></tr>)}</tbody></table></div>}
   {data.next_cursor&&<button className="btn" disabled={busy} onClick={()=>load(data.next_cursor)}>Load more theses</button>}
  </>}
  {history&&<section aria-label="Versioned performance reviews" className="border-y border-[var(--border-default)] py-3 space-y-2"><div className="flex justify-between"><h3>{history.row.title} · assessment history</h3><button onClick={()=>setHistory(null)}>Close history</button></div>{history.rows.length===0?<p>No performance assessments have been recorded.</p>:history.rows.map(review=><details key={review.id}><summary>{human(review.performance_evaluation.assessment)} · {date(review.created_at)}</summary><p className="whitespace-pre-wrap">{review.note}</p><p>Window {date(review.performance_evaluation.from)} to {date(review.performance_evaluation.to)} · declared {date(review.performance_evaluation.window_declared_at)}</p><p>Fees: {review.performance_evaluation.fees_assumption}</p><p>Slippage: {review.performance_evaluation.slippage_assumption}</p><p className="break-all">Evidence references: {review.performance_evaluation.evidence_refs.join(' · ')||'None recorded'}</p><OriginalForecast record={review.performance_evaluation.original_forecast}/></details>)}<nav aria-label="Performance review pages"><button disabled={busy||history.page===0} onClick={()=>showHistory(history.row,history.page-1)}>Newer reviews</button><span> Page {history.page+1} </span><button disabled={busy||!history.hasMore} onClick={()=>showHistory(history.row,history.page+1)}>Older reviews</button></nav></section>}
  {editing&&<AssessmentEditor row={editing} supabase={supabase} orgId={orgId} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load()}}/>}
 </section>
}
function OriginalForecast({record}){return record?<div className="space-y-2 text-xs"><p>Original decision {date(record.occurred_at)} · recorded {date(record.recorded_at)}</p>{Object.entries(record.words||{}).map(([key,value])=><p key={key} className="whitespace-pre-wrap"><strong>{human(key)}: </strong>{String(value)}</p>)}<p>Original horizon: {record.fields?.time_horizon?.after||'Not recorded'} · Original stance: {record.fields?.stance?.after||'Not recorded'}</p></div>:<p>Original forecast is unavailable; no past words have been reconstructed.</p>}
function AssessmentEditor({row,supabase,orgId,onClose,onSaved}){
 const previous=row.latest_review?.evaluation,original=row.original_forecast
 const begin=previous?.from||new Date(Math.ceil(Date.parse(original?.occurred_at||row.created_at)/1000)*1000).toISOString(),end=previous?.to||new Date(Math.max(Date.now(),Date.parse(begin)+60000)).toISOString()
 const [form,setForm]=useState({from:local(begin),to:local(end),assessment:'pending',note:'',fees:previous?.fees_assumption||'Not assessed',slippage:previous?.slippage_assumption||'Not assessed',references:''}),[busy,setBusy]=useState(false),[error,setError]=useState(null),dialog=useRef(null),operation=useRef(null),alive=useRef(true),heading=useId()
 useEffect(()=>{alive.current=true;const focused=document.activeElement;dialog.current?.showModal();return()=>{alive.current=false;focused?.focus?.()}},[])
 const set=(key,value)=>setForm(old=>({...old,[key]:value}))
 const save=async event=>{event.preventDefault();setBusy(true);setError(null);try{
  // datetime-local displays seconds; retain the server's precise window when unchanged.
  const from=previous&&form.from===local(previous.from)?previous.from:new Date(form.from).toISOString(),to=previous&&form.to===local(previous.to)?previous.to:new Date(form.to).toISOString(),sameWindow=previous&&from===previous.from&&to===previous.to,review={from,to,assessment:form.assessment,note:form.note,fees_assumption:form.fees,slippage_assumption:form.slippage,evidence_refs:form.references.split('\n').map(s=>s.trim()).filter(Boolean),previous_review_id:sameWindow?row.latest_review.id:null},signature=JSON.stringify(review);if(operation.current?.signature!==signature)operation.current={signature,id:crypto.randomUUID()};await savePerformanceReview(supabase,orgId,row.id,review,operation.current.id);if(alive.current)await onSaved()}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 return <dialog ref={dialog} aria-labelledby={heading} className="intel-chart-study-dialog" onCancel={e=>{e.preventDefault();onClose()}}><div className="flex justify-between gap-3"><h2 id={heading}>Record a performance assessment</h2><button disabled={busy} onClick={onClose}>Close</button></div><p>{row.title}</p><details><summary>Original forecast</summary><OriginalForecast record={original}/></details><form onSubmit={save} className="space-y-3"><div className="flex flex-wrap gap-3"><label>Window starts (device time)<input type="datetime-local" step="1" required value={form.from} onChange={e=>set('from',e.target.value)}/></label><label>Window ends (device time)<input type="datetime-local" step="1" required value={form.to} onChange={e=>set('to',e.target.value)}/></label></div><label>Assessment<select value={form.assessment} onChange={e=>set('assessment',e.target.value)}>{['pending','ambiguous','supported','contradicted','mixed','invalidated'].map(value=><option key={value} value={value}>{human(value)}</option>)}</select></label><label>Your assessment<textarea required minLength={12} maxLength={8000} rows={3} value={form.note} onChange={e=>set('note',e.target.value)}/></label><label>Evidence references · one per line<textarea rows={2} maxLength={10000} value={form.references} onChange={e=>set('references',e.target.value)}/></label><label>Fee assumptions<input maxLength={2000} value={form.fees} onChange={e=>set('fees',e.target.value)}/></label><label>Slippage assumptions<input maxLength={2000} value={form.slippage} onChange={e=>set('slippage',e.target.value)}/></label><p className="intel-analysis-caption">This saves a new private review and its recording time. Completed assessments need a window after the original forecast, an ended period, notes and evidence references. Pending and ambiguous outcomes remain visible. No return or executed trade is inferred.</p>{error&&<p role="alert">{error}</p>}<button className="btn btn--primary" disabled={busy}>{busy?'Saving…':'Save new assessment'}</button></form></dialog>
}
