import {assertEquals as eq} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {CMC_FOCUS_IDS,quoteGroupRows,planQuoteGroups,quoteRefreshSeconds,requestGroupedQuotes} from './cmc-quote-groups.ts'
const result=(ids:string[],state='fresh')=>({payload:{data:ids.map(id=>({id:Number(id),quote:{price:10,last_updated:'2026-09-10T18:00:00Z'}}))},state,reason:null,provenance:{provider:'coinmarketcap',observedAt:'2026-09-10T18:00:00Z',fetchedAt:'2026-09-10T18:00:10Z',expiresAt:'2026-09-10T18:01:10Z',sourceUrl:'https://coinmarketcap.com/'}} as any)
Deno.test('different major asset pages reuse one stable minute batch',()=>{for(const id of CMC_FOCUS_IDS)eq(planQuoteGroups([id]),[CMC_FOCUS_IDS]);eq(quoteRefreshSeconds({id:CMC_FOCUS_IDS.join(',')}),60);eq(quoteRefreshSeconds({id:'999'}),300)})
Deno.test('universe cohorts have at most 250 exact IDs and omit the independent hot set',()=>{const ids=Array.from({length:1000},(_,i)=>String(i+1));const rows=quoteGroupRows([...ids,...CMC_FOCUS_IDS]);eq(rows.length,999);eq(new Set(rows.map(r=>r.quote_batch_ids.join(','))).size,4);eq(rows.every(r=>r.quote_batch_ids.includes(r.provider_id)&&r.quote_batch_ids.length<=250&&!r.quote_batch_ids.includes('1')),true);eq(quoteGroupRows([...ids].reverse()),quoteGroupRows(ids))})
Deno.test('missing schema, invalid groups and off-universe IDs cannot expand into arbitrary requests',()=>{eq(planQuoteGroups(['21','22'],[{provider_id:'21',quote_batch_ids:['22']}]),[['21','22']]);eq(planQuoteGroups(['21'],[{provider_id:'21',quote_batch_ids:['21','https://bad']}]),[['21']]);eq(planQuoteGroups(['21'],[{provider_id:'21',quote_batch_ids:Array(251).fill('21')}]),[['21']])})
Deno.test('batch results project only requested identities and their observation clocks',async()=>{const calls:any[]=[];const r=await requestGroupedQuotes({id:'1027'},undefined,async(_name,params)=>{calls.push(params);return result(CMC_FOCUS_IDS)});eq(calls,[{id:CMC_FOCUS_IDS.join(',')}]);eq(r.payload?.data.map((x:any)=>x.id),[1027]);eq(r.provenance.observedAt,'2026-09-10T18:00:00.000Z');eq(r.state,'fresh')})
Deno.test('multi-cohort baskets retain missing coverage and cap expansion to four calls',async()=>{const ids=['31','32','33','34','35'],rows=ids.map(id=>({provider_id:id,quote_batch_ids:[id,String(Number(id)+10)]}));const q:any={select:()=>q,eq:()=>q,in:()=>q,limit:()=>Promise.resolve({data:rows})};const calls:any[]=[];const r=await requestGroupedQuotes({id:ids.join(',')},{supabase:{from:()=>q}},async(_name,p)=>{calls.push(p);return result(['31'])});eq(calls.length,1);eq(calls[0].id,ids.join(','));eq(r.state,'stale');eq(r.reason,'missing_coverage')})
Deno.test('provider denial remains unavailable and never invents an empty fresh response',async()=>{const r=await requestGroupedQuotes({id:1},undefined,async()=>({...result([]),payload:null,state:'unsupported',reason:'insufficient_entitlement'}));eq(r.payload,null);eq(r.state,'unsupported');eq(r.reason,'insufficient_entitlement')})
Deno.test('empty successful provider payload is unavailable coverage',async()=>{const r=await requestGroupedQuotes({id:1},undefined,async()=>result([]));eq(r.payload,null);eq(r.state,'unavailable');eq(r.reason,'missing_coverage')})
