import {assertEquals,assertRejects,assertThrows} from 'jsr:@std/assert'
import {deliveryMessage,sendIntelAlert,runAlertDeliveries} from './alert-delivery.ts'
const target={chatId:'123456789',eventId:'30000000-0000-4000-8000-000000000001',firedAt:'2026-09-11T12:00:00Z',trigger:'chart_price',title:'Original <b>words</b>'}
const reply=(body:unknown,status=200)=>async()=>new Response(typeof body==='string'?body:JSON.stringify(body),{status})
Deno.test('private delivery retains authored title as plain text and exports no observations or notes',()=>{const body=deliveryMessage({...target,...{privateNote:'private',value:123}});assertEquals(body.text.includes('<b>words</b>'),true);assertEquals('parse_mode' in body,false);assertEquals(JSON.stringify(body).includes('privateNote'),false);assertThrows(()=>deliveryMessage({...target,chatId:'-1234'}))})
Deno.test('accepted requires affirmative provider body and message reference, never means read',async()=>{assertEquals(await sendIntelAlert(target,'test',reply({ok:true,result:{message_id:42}})),{outcome:'provider_accepted',http:200,message:'42'});assertEquals((await sendIntelAlert(target,'test',reply({ok:true}))).outcome,'unknown')})
Deno.test('only definite rate-limit rejection retries with bounded wait',async()=>{assertEquals(await sendIntelAlert(target,'test',reply({ok:false,error_code:429,parameters:{retry_after:9000}},429)),{outcome:'retry',http:429,retrySeconds:3600});assertEquals((await sendIntelAlert(target,'test',reply({ok:false,error_code:500},500))).outcome,'unknown')})
Deno.test('network, malformed and oversized responses are uncertain without automatic retry',async()=>{for(const transport of [async()=>{throw Error('sensitive transport')},reply('bad'),reply('x'.repeat(40000))])assertEquals((await sendIntelAlert(target,'test',transport)).outcome,'unknown')})
Deno.test('definite refusal fails and request cannot follow redirects',async()=>{let request:RequestInit|undefined;const result=await sendIntelAlert(target,'test',async(_url,opts)=>{request=opts;return reply({ok:false},403)()});assertEquals(result.outcome,'failed');assertEquals(request?.redirect,'error')})
Deno.test('disabled transport does not claim jobs or touch provider',async()=>{assertEquals(await runAlertDeliveries({rpc(){throw Error('must not claim')}},{enabled:false,token:''}),{enabled:false,claimed:0,accepted:0})})
Deno.test('consent checked immediately before sending and cancelled when revoked',async()=>{const calls:string[]=[];const db={rpc(name:string){calls.push(name);return {data:name==='intel_claim_alert_deliveries'?[{id:'d',lease:'l'}]:name==='intel_alert_delivery_target'?null:true}}};await runAlertDeliveries(db,{enabled:true,token:'test',transport:async()=>{throw Error('must not send')}});assertEquals(calls,['intel_claim_alert_deliveries','intel_alert_delivery_target','intel_finish_alert_delivery'])})
Deno.test('failed receipt stops the run, no misleading accepted count',async()=>{const db={rpc(name:string){return {data:name==='intel_claim_alert_deliveries'?[{id:'d',lease:'l'}]:name==='intel_alert_delivery_target'?target:false}}};await assertRejects(()=>runAlertDeliveries(db,{enabled:true,token:'test',transport:reply({ok:true,result:{message_id:1}})}),Error,'receipt_conflict')})
Deno.test('delivery text keeps each line readable: evidence label, then the recorded time after a space',()=>{const lines=deliveryMessage(target).text.split('\n');assertEquals(lines[0],'Investor Intel alert');assertEquals(lines.includes('Recorded 2026-09-11T12:00:00.000Z'),true);assertEquals(lines.some((line)=>/^Recorded\d/.test(line)),false)})
