import {assertEquals as eq,assertRejects} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {readAssetVenueContext} from './asset-venue-service.ts'
const now=Date.parse('2026-09-11T12:00:00Z'),iso=new Date(now).toISOString()
function database(overrides:Record<string,any>={}){
 const requests:any[]=[]
 const defaults:any={market_assets:{source_provider:'coingecko',provider_id:'bitcoin',normalized_symbol:'BTC'},exchange_asset_mappings:null,intel_market_observations:[],exchange_latest_orderbook:[{provider:'venue',provider_symbol:'BTC-USD',as_of:iso,bid_price:10,ask_price:11,bid_qty:0,ask_qty:2}],exchange_latest_tickers:[{provider:'venue',provider_symbol:'BTC-USD',quote_asset:'USD'}]}
 return {requests,from(table:string){const r:any={table,filters:[]};requests.push(r);const q:any={};for(const m of ['select','eq','in','gte','lte','gt','order','ilike','limit'])q[m]=(...a:any[])=>{r.filters.push([m,...a]);return q};const response=()=>overrides[table]?.error?overrides[table]:{data:table in overrides?overrides[table]:defaults[table],error:null};q.then=(resolve:any)=>Promise.resolve(response()).then(resolve);q.maybeSingle=()=>Promise.resolve(response());return q}}
}
Deno.test('venue navigation uses bounded retained reads and keeps zero depth',async()=>{const db=database();let calls=0;const r=await readAssetVenueContext(db,{canonicalKey:'native:bitcoin'},async()=>{calls++;return {}},now);eq(calls,0);eq(r.depth.status,'available');eq(r.depth.quotes.find(q=>q.side==='sell')?.levels[0].quantity,0);eq(r.derivatives.evaluated_at,iso);eq(db.requests.find(r=>r.table==='intel_market_observations')?.filters.some((f:any)=>f[0]==='limit'&&f[1]===201),true);eq(db.requests.find(r=>r.table==='exchange_latest_orderbook')?.filters.some((f:any)=>f[0]==='limit'&&f[1]===8),true)})
Deno.test('explicit venue refresh is exactly two shared bounded capabilities and isolates a failed source',async()=>{const calls:any[]=[];const r=await readAssetVenueContext(database(),{canonicalKey:'native:bitcoin',refresh:true},async(c,p)=>{calls.push([c,p]);if(c==='derivativePairs')throw Error('secret token');return {state:'fresh'}},now);eq(calls,[['derivativePairs',{crypto_id:'1',start:'1',limit:'50'}],['liquidationAssets',{crypto_id:'1',start:'1',limit:'50'}]]);eq(r.refreshResults.map(r=>r.state),['error','fresh']);eq(JSON.stringify(r).includes('secret token'),false)})
Deno.test('unverified symbol mapping cannot request depth or a derivative provider',async()=>{const db=database({market_assets:{source_provider:'coingecko',provider_id:'other-bitcoin',normalized_symbol:'BTC'},exchange_asset_mappings:null});let calls=0;const r=await readAssetVenueContext(db,{canonicalKey:'market:coingecko:other-bitcoin',refresh:true},async()=>{calls++;return {}},now);eq(calls,0);eq(r.depth.status,'unverified');eq(db.requests.some(r=>r.table==='exchange_latest_orderbook'),false)})
Deno.test('failed, malformed and oversized venue reads stay errors, never empty coverage',async()=>{for(const overrides of [{intel_market_observations:{error:{message:'private db detail'}}},{exchange_latest_orderbook:null},{exchange_latest_tickers:Array.from({length:33},()=>({}))},{exchange_asset_mappings:{error:{message:'private detail'}}}]){const r=await readAssetVenueContext(database(overrides),{canonicalKey:'native:bitcoin'},undefined,now);eq(r.derivatives.status==='error'||r.depth.status==='error',true);eq(JSON.stringify(r).includes('private detail'),false)}})
Deno.test('invalid identity is rejected before any source read or refresh',async()=>{const db=database();for(const canonicalKey of ['', 'BTC\n', 'a'.repeat(241)])await assertRejects(()=>readAssetVenueContext(db,{canonicalKey,refresh:true}),Error,'invalid_venue_identity');eq(db.requests.length,0)})
