import {assertEquals as eq,assert,assertThrows} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {aggregateCompletedBars,chartTimeframeAlignment} from './chart-timeframes.ts'
const hour=3600000,t=Date.UTC(2026,7,31)
const bars=(n:number)=>Array.from({length:n},(_,i)=>({t:t+i*hour,closedAt:t+(i+1)*hour-1,recordedAt:t+(i+1)*hour,o:100+i*.1-.05,h:101+i*.1,l:99+i*.1,c:100+i*.1,v:100,volumeKind:'period' as const}))
const accelerating=()=>bars(400).map((b,i)=>{const extra=i*i*.0001;return {...b,o:b.o+extra,h:b.h+extra,l:b.l+extra,c:b.c+extra}})
Deno.test('higher timeframes aggregate every exact UTC source period with actual OHLC',()=>{const r=aggregateCompletedBars(bars(8),hour,4*hour,t+8*hour);eq(r.bars.length,2);eq(r.bars[0],{t,closedAt:t+4*hour-1,o:99.95,h:101.3,l:99,c:100.3,v:400,volumeKind:'period',recordedAt:t+4*hour})})
Deno.test('overlapping CMC adjusted-volume snapshots use the final value and never become period volume',()=>{const r=aggregateCompletedBars(bars(4).map((b,i)=>({...b,v:100+i,volumeKind:'snapshot',volumeUnit:'USD'})),hour,4*hour,t+4*hour);eq(r.bars[0].v,103);eq(r.bars[0].volumeKind,'snapshot');eq(r.bars[0].volumeUnit,'USD')})
Deno.test('missing and unfinished source periods cannot fabricate larger candles',()=>{const b=bars(8).filter((_,i)=>i!==1);eq(aggregateCompletedBars(b,hour,4*hour,t+8*hour).bars.map(b=>b.t),[t+4*hour]);eq(aggregateCompletedBars(bars(8),hour,4*hour,t+7*hour).bars.length,1);eq(aggregateCompletedBars(bars(4).map(b=>({...b,closedAt:b.t})),hour,4*hour,t+4*hour).bars,[])})
Deno.test('weekly periods begin Monday UTC and exclude partial edge weeks',()=>{const r=aggregateCompletedBars(bars(24*7+5),hour,24*7*hour,t+(24*7+5)*hour);eq(r.bars.length,1);eq(r.bars[0].t,t);eq(r.bars[0].closedAt,t+7*24*hour-1)})
Deno.test('timeframe agreement only counts frames with completed DEMA and RSI warmups',()=>{const r=chartTimeframeAlignment(accelerating(),{at:t+400*hour,intervalMs:hour});eq(r.rows.map(r=>r.label),['1 hour','4 hour','1 day','1 week']);eq(r.covered,2);eq(r.agreement,'Upward agreement across covered frames');eq(r.rows[0].rsi,100);eq(r.rows[2].state,'Unavailable');assert(r.rows[2].gaps.some(x=>x?.includes('85 contiguous closes')))})
Deno.test('incompatible volume remains explicitly unavailable while close-based states still work',()=>{const r=chartTimeframeAlignment(accelerating().map(b=>({...b,volumeKind:'snapshot',volumeUnit:'USD'})),{at:t+400*hour,intervalMs:hour});eq(r.rows[0].vwap,null);assert(r.rows[0].gaps.some(x=>x?.includes('volume snapshots')));eq(r.rows[0].state,'Upward agreement')})
Deno.test('old or delayed captures do not leak future knowledge into timeframe alignment',()=>{const b=bars(400),at=t+100*hour;eq(chartTimeframeAlignment(b,{at,intervalMs:hour,knownOnly:true}),chartTimeframeAlignment(b.slice(0,100),{at,intervalMs:hour,knownOnly:true}));const r=chartTimeframeAlignment(b.map(b=>({...b,recordedAt:t+500*hour})),{at,intervalMs:hour,knownOnly:true});eq(r.covered,0)})
Deno.test('a recent gap resets warmups instead of stitching old observations into an indicator',()=>{const b=bars(400).filter((_,i)=>i!==390),r=chartTimeframeAlignment(b,{at:t+400*hour,intervalMs:hour});eq(r.rows[0].bars,9);eq(r.rows[0].dema,null);eq(r.rows[0].state,'Unavailable')})
Deno.test('unknown intervals fail closed and invalid periods do not allocate work',()=>{eq(chartTimeframeAlignment(bars(4),{at:t+4*hour,intervalMs:null}).rows,[]);assertThrows(()=>aggregateCompletedBars(bars(4),0,hour,t));assertThrows(()=>aggregateCompletedBars(bars(4),hour,90*60000,t));assertThrows(()=>chartTimeframeAlignment(bars(4),{at:NaN,intervalMs:hour}))})

Deno.test('a linear price series whose DEMA equals its close stays neutral despite floating-point noise',()=>{const r=chartTimeframeAlignment(bars(400),{at:t+400*hour,intervalMs:hour});eq(r.rows[0].trend,'At DEMA');eq(r.rows[0].state,'Mixed / neutral')})
