import {assertEquals as eq,assertRejects} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {chartReviewService} from './chart-review-service.ts'
const viewer='10000000-0000-4000-8000-000000000001',id='20000000-0000-4000-8000-000000000001',token='a'.repeat(64),now=1788998400123
const state={title:'Private snapshot',capturedAt:now,source:{provider:'coinmarketcap',currency:'USD'},policy:{retain:false,export:false},layout:{schemaVersion:1,asset:'native:bitcoin',range:{from:now-10000,to:now},drawings:[],studies:[]},bars:null,sourceHash:'hash',barCount:10}
function db(audience='owner',result:any={rows:[]},snapshot=state){const calls:any[]=[];return {calls,rpc:async(name:string,args:any)=>{calls.push([name,args]);return {data:name==='intel_resolve_chart_share'?{snapshot,audience,drawingIds:[],expiresAt:'2026-09-12T00:00:00Z'}:result,error:null}}}}
const env=()=>undefined
Deno.test('review reads verify current source rights and bind the verified viewer, never client identity',async()=>{const d=db();await chartReviewService(d,viewer,{operation:'review_list',token,page:1,userId:'forged',orgId:'forged'},env);eq(d.calls[0],['intel_resolve_chart_share',{p_token:token,p_viewer:viewer}]);eq(d.calls[1],['intel_chart_review_page',{p_token:token,p_user:viewer,p_page:1}])})
Deno.test('anonymous and public-link readers cannot open the private review conversation',async()=>{await assertRejects(()=>chartReviewService(db(),null,{operation:'review_list',token},env));const d=db('public',{rows:[]},{...state,policy:{retain:true,export:true}});await assertRejects(()=>chartReviewService(d,viewer,{operation:'review_list',token},()=> 'true'),Error,'chart_review_unavailable');eq(d.calls.length,1)})
Deno.test('organization review cannot bypass current source sharing policy',async()=>{const d=db('org');await assertRejects(()=>chartReviewService(d,viewer,{operation:'review_list',token},env),Error,'chart_share_source_unavailable');eq(d.calls.length,1)})
Deno.test('review saves retain exact original text and anchors but omit arbitrary personal data',async()=>{const d=db();await chartReviewService(d,viewer,{operation:'review_save',token,operationId:id,revision:0,text:'Original <script>words</script>',anchor:{t:now,price:77123.12345678,position:99},portfolioNotes:'Excluded'},env);eq(d.calls[1][1],{p_token:token,p_user:viewer,p_id:null,p_revision:0,p_operation:id,p_anchor:{t:now,price:77123.12345678},p_text:'Original <script>words</script>'})})
Deno.test('out-of-snapshot anchors and malformed comments are rejected before any write',async()=>{for(const patch of [{anchor:{t:now+1,price:100}},{anchor:{t:now,price:Infinity}},{text:'a'.repeat(2001)},{text:'bad\u0000text'},{revision:-1},{operationId:'invalid'}]){const d=db();await assertRejects(()=>chartReviewService(d,viewer,{operation:'review_save',token,operationId:id,revision:0,text:'Note',anchor:{t:now,price:100},...patch},env));eq(d.calls.length,1)}})
Deno.test('deletion includes expected revision and cannot select another org or author',async()=>{const d=db('owner',true);eq(await chartReviewService(d,viewer,{operation:'review_delete',token,id,revision:4,userId:'forged'},env),{deleted:true});eq(d.calls[0],['intel_delete_chart_comment',{p_token:token,p_user:viewer,p_id:id,p_revision:4}]);eq(d.calls.length,1);await assertRejects(()=>chartReviewService(db(),viewer,{operation:'review_list',token,page:201},env))})

Deno.test('author cleanup is bounded, binds the authenticated identity, and does not resolve expired prices',async()=>{
 const d=db('owner',{rows:Array.from({length:6},()=>({id,text:'My own note'})),hasMore:true})
 const result=await chartReviewService(d,viewer,{operation:'review_owned',token,page:1,userId:'forged'},env)
 eq(d.calls,[['intel_chart_owned_comments',{p_token:token,p_user:viewer,p_page:1}]]);eq(result.rows.length,5);eq(result.hasMore,true)
 await assertRejects(()=>chartReviewService(db(),null,{operation:'review_owned',token},env));await assertRejects(()=>chartReviewService(db(),viewer,{operation:'review_owned',token,page:201},env))
})
