import {assertEquals as eq,assertThrows,assertRejects} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {chartAlertConfig,chartAlertService,chartAlertAssetAliases} from './chart-alert-service.ts'
const actor={orgId:'10000000-0000-4000-8000-000000000001',userId:'20000000-0000-4000-8000-000000000001'},id='30000000-0000-4000-8000-000000000001'
const config={asset:'native:bitcoin',threshold_usd:77123.12345678,direction:'above',title:'Price crossing',note:'Original <script>plain words</script>',anchor:{t:1788998400000,price:77123.12345678}}
const mock=(data:any)=>{const calls:any[]=[];const q:any=new Proxy({},{get:(_,key)=>key==='then'?(resolve:any)=>Promise.resolve({data,error:null}).then(resolve):(...args:any[])=>{calls.push([key,...args]);return q}});return {calls,from:(...args:any[])=>{calls.push(['from',...args]);return q},rpc:(...args:any[])=>{calls.push(['rpc',...args]);return q}}}
Deno.test('history rehearsal fixes scope, window and permitted providers on the server',async()=>{
 const db=mock({previewOnly:true,examples:[]}),now=1789156800000
 await chartAlertService(db,actor,{operation:'alert_rehearsal',id,p_allowed_providers:['forged'],from:0,orgId:'foreign'},{now,env:k=>k==='CMC_ALLOW_HISTORICAL_RETENTION'?'true':undefined})
 eq(db.calls[0][2],{p_org:actor.orgId,p_user:actor.userId,p_rule:id,p_from:new Date(now-86400000).toISOString(),p_to:new Date(now).toISOString(),p_allowed_providers:['coinmarketcap']})
 const expired=mock({previewOnly:true,examples:[]});await chartAlertService(expired,actor,{operation:'alert_rehearsal',id},{now,env:k=>k==='CMC_ALLOW_HISTORICAL_RETENTION'?'true':k==='CMC_SOURCE_POLICY_EXPIRES_AT'?'2026-01-01':undefined});eq(expired.calls[0][2].p_allowed_providers,[])
 await assertRejects(()=>chartAlertService(mock(null),actor,{operation:'alert_rehearsal',id}),Error,'chart_alert_storage_unavailable')
})
Deno.test('general alert save fixes actor scope, preserves operation id and excludes arbitrary fields',async()=>{
 const db=mock({rule:{id}}),body={operation:'alert_general_save',operationId:id,revision:0,entityId:id,trigger:'price_move',config:{threshold_pct:0,note:'original',title:'QA',visibility:'private'},active:false,cooldownMinutes:15,userId:'forged',orgId:'forged',chart_state:{fake:true}}
 await chartAlertService(db,actor,body);eq(db.calls[0][2],{p_org:actor.orgId,p_user:actor.userId,p_id:null,p_revision:0,p_operation:id,p_entity:id,p_trigger:'price_move',p_config:body.config,p_active:false,p_cooldown:15})
 for(const patch of [{trigger:'chart_price'},{trigger:'thesis_condition'},{entityId:'BTC'},{revision:-1},{config:[]},{operationId:'retry'}])await assertRejects(()=>chartAlertService(db,actor,{...body,...patch}))
})
Deno.test('alert chart history uses reviewed identity aliases without joining unrelated chains or ticker lookalikes',()=>{
 eq(chartAlertAssetAliases('market:coinmarketcap:1').includes('bip122:native:BTC'),true);eq(chartAlertAssetAliases('bip122:native:BTC').includes('market:coinmarketcap:1'),true)
 eq(chartAlertAssetAliases('eip155:8453:native').includes('eip155:1:native'),false);eq(chartAlertAssetAliases('market:coinmarketcap:1027').includes('eip155:8453:native'),false)
 eq(chartAlertAssetAliases('market:coinmarketcap:999999'),['market:coinmarketcap:999999']);assertThrows(()=>chartAlertAssetAliases('BTC'))
 const mint='So11111111111111111111111111111111111111112';eq(chartAlertAssetAliases('solana:mainnet/spl:'+mint).includes('solana:'+mint),true)
})
Deno.test('bounded chart history ignores forged owner selection and validates both period and keyset cursor',async()=>{
 const db=mock({rows:[],nextCursor:null}),from=1788998400000,to=from+1000;await chartAlertService(db,actor,{operation:'alert_history',asset:'native:bitcoin',from,to,userId:'forged',p_limit:100000});const args=db.calls[0][2];eq(args.p_org,actor.orgId);eq(args.p_user,actor.userId);eq(args.p_from,new Date(from).toISOString());eq(args.p_cursor,null);eq('p_limit' in args,false)
 for(const patch of [{from:NaN},{to:from-1},{to:from+367*86400000},{cursor:{at:'invalid',id}},{cursor:{at:new Date(from).toISOString(),id:'bad'}}])await assertRejects(()=>chartAlertService(db,actor,{operation:'alert_history',asset:'native:bitcoin',from,to,...patch}))
})
Deno.test('chart alert config keeps exact anchors and words but excludes ambient private fields',()=>{const r=chartAlertConfig({...config,portfolioNotes:'excluded',snapshot:{secret:1},delivery:'telegram',method:'invented'});eq(r.threshold_usd,config.threshold_usd);eq(r.anchor,config.anchor);eq(r.note,config.note);eq(r.delivery,'in_app');eq('snapshot' in r,false);eq('portfolioNotes' in r,false)})
Deno.test('condition behavior validates duration, rearm and reset margin without losing valid zero',()=>{eq(chartAlertConfig({...config,hysteresis_pct:0}).hysteresis_pct,0);eq(chartAlertConfig({...config,condition:'sustained',sustain_minutes:30,repeat:'once'}).sustain_minutes,30);for(const patch of [{condition:'sustained',sustain_minutes:0},{condition:'crossing',sustain_minutes:30},{hysteresis_pct:NaN},{hysteresis_pct:51},{repeat:'always'},{sustain_minutes:15.5}])assertThrows(()=>chartAlertConfig({...config,...patch}))})
Deno.test('chart conditions reject tickers, nonfinite or zero prices, unsafe timestamps and excess text',()=>{for(const patch of [{asset:'BTC'},{threshold_usd:NaN},{threshold_usd:Infinity},{threshold_usd:0},{threshold_usd:'100'},{direction:'sell'},{note:'x'.repeat(2001)},{anchor:{t:Infinity,price:100}},{title:'bad\u0000title'}])assertThrows(()=>chartAlertConfig({...config,...patch}))})
Deno.test('chart save uses authenticated identity, revision and operation without arbitrary body fields',async()=>{const db=mock({id});await chartAlertService(db,actor,{operation:'alert_save',operationId:id,revision:0,active:false,cooldownMinutes:15,config,userId:'spoof',orgId:'spoof'});const args=db.calls[0][2];eq(args.p_user,actor.userId);eq(args.p_org,actor.orgId);eq(args.p_active,false);eq(args.p_operation,id);eq(args.p_config.delivery,'in_app')})
Deno.test('chart evidence preview cannot commit or target another actor from client fields',async()=>{const db=mock({results:[{state:'baseline'}]});await chartAlertService(db,actor,{operation:'alert_preview',id,p_commit:true,p_user:'spoof'});eq(db.calls[0][2],{p_limit:1,p_rule:id,p_org:actor.orgId,p_user:actor.userId,p_commit:false})})
Deno.test('chart audit reads retain owner organization bounds and one page plus sentinel',async()=>{const db=mock(Array.from({length:21},(_,id)=>({id})));const r=await chartAlertService(db,actor,{operation:'alert_audit',id,page:3});eq(r.rows.length,20);eq(r.hasMore,true);eq(db.calls.filter(c=>c[0]==='eq'),[['eq','org_id',actor.orgId],['eq','user_id',actor.userId],['eq','rule_id',id]]);eq(db.calls.find(c=>c[0]==='range'),['range',60,80])})
Deno.test('invalid operation identifiers, cooldowns, versions and inaccessible rules fail explicitly',async()=>{for(const patch of [{revision:-1},{operationId:'retry'},{cooldownMinutes:0},{active:'true'}])await assertRejects(()=>chartAlertService(mock({}),actor,{operation:'alert_save',operationId:id,revision:0,active:false,cooldownMinutes:15,config,...patch}));await assertRejects(()=>chartAlertService(mock({results:[]}),actor,{operation:'alert_preview',id}),Error,'chart_alert_not_found');await assertRejects(()=>chartAlertService(mock({}),actor,{operation:'alert_audit',id,page:1001}))})
