import {assertEquals as eq,assertThrows,assertStringIncludes as includes} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {chartImage} from './chart-image.ts'
const id='20000000-0000-4000-8000-000000000001',t=1788998400000
const bars=Array.from({length:60},(_,i)=>({t:t+i*3600000,o:100+i,h:104+i,l:98+i,c:102+i,v:1000+i}))
export const imageFixture={schemaVersion:1,title:'Bitcoin · research checkpoint',capturedAt:t+61*3600000,calculationVersion:'chart-1',source:{provider:'coingecko',currency:'USD',sourceUrl:'https://www.coingecko.com/en/coins/bitcoin',timestampMeaning:'candle_close'},sourceHash:'a'.repeat(64),bars,layout:{schemaVersion:1,asset:'native:bitcoin',range:{from:t,to:t+60*3600000},mode:'candles',scale:'linear',timezone:'America/Chicago',volume:true,studies:[{id:'ema',type:'ema',params:{period:20}},{id:'rsi',type:'rsi',params:{period:14}}],drawings:[{id,tool:'text',text:'Original authored note: wait for confirmation, then review.',anchors:[{t:t+20*3600000,price:130}]}]}}
Deno.test('static export includes price, study panes, clock and provenance but excludes annotations by default',()=>{const r=chartImage(imageFixture);includes(r.svg,'<rect');includes(r.svg,'RSI');includes(r.svg,'coingecko');includes(r.svg,'America/Chicago');includes(r.svg,'Series SHA-256');includes(r.svg,'static auto-fit');eq(r.svg.includes('Original authored note'),false);eq(r.annotationCount,0);eq(r.pngAvailable,true)})
Deno.test('export preserves selected full notes without executing markup or fetching user URLs',()=>{const note='<script>alert(1)</script><image href="https://evil.test/private"/>',r=chartImage({...imageFixture,title:note,layout:{...imageFixture.layout,drawings:[{...imageFixture.layout.drawings[0],text:note}]}},[id]);eq(r.svg.includes('<script>'),false);eq(r.svg.includes('<image href='),false);includes(r.svg,'&lt;script&gt;');includes(r.svg,'&quot;https://evil.test/private&quot;');eq(r.annotationCount,1)})
Deno.test('all scales generate finite coordinates for flat prices and retain true axis semantics',()=>{for(const scale of ['linear','log','percent','indexed']){const r=chartImage({...imageFixture,bars:bars.map(b=>({...b,o:100,h:100,l:100,c:100})),layout:{...imageFixture.layout,scale}});eq(/NaN|Infinity/.test(r.svg),false);includes(r.svg,`${scale} scale`);if(scale==='percent')includes(r.svg,'%')}})
Deno.test('out-of-window data warms studies but does not plot future prices or mutate snapshot content',()=>{const original=JSON.stringify(imageFixture),r=chartImage({...imageFixture,bars:[...bars,{t:t+100*3600000,c:999999}],layout:{...imageFixture.layout,mode:'line'}});eq(r.svg.includes('999999'),false);eq(JSON.stringify(imageFixture),original)})
Deno.test('close-only data never exports manufactured candle wicks and gap lines are broken',()=>{const r=chartImage({...imageFixture,bars:[0,1,4].map(i=>({t:t+i*3600000,c:100+i})),layout:{...imageFixture.layout,studies:[],drawings:[],volume:false}});eq((r.svg.match(/<polyline /g)||[]).length,2);eq(r.svg.includes('Volume'),false)})
Deno.test('export rejects forged annotation selection and missing visible bars',()=>{assertThrows(()=>chartImage(imageFixture,['20000000-0000-4000-8000-000000000099']),Error,'annotations');assertThrows(()=>chartImage({...imageFixture,bars:[]}),Error,'empty')})
Deno.test('maximum supported bar and study budgets avoid argument-stack overflow',()=>{const data=Array.from({length:5000},(_,i)=>({t:t+i*3600000,c:100+i})),state={...imageFixture,bars:data,layout:{...imageFixture.layout,range:{from:t,to:t+5000*3600000},studies:Array.from({length:20},(_,i)=>({id:`s${i}`,type:'sma',params:{period:2+i}}))}};try{const r=chartImage(state);eq(r.svg.length<2500000,true)}catch(e){eq((e as Error).message,'chart_snapshot_export_size_limit')}})

Deno.test('replay exports exclude unfinished and later-recorded prices before study calculation',()=>{
 const cutoff=t+31*3600000,eligible=bars.slice(0,31).map(b=>({...b,closedAt:b.t+3600000-1,recordedAt:b.t+3600000-1})),late={...bars[31],t:cutoff-500,c:987654.123,h:987655,closedAt:cutoff-1,recordedAt:cutoff+1}
 const base={...imageFixture,layout:{...imageFixture.layout,replay:{at:cutoff,knownOnly:true}},replaySeriesHash:'subset'}
 const expected=chartImage({...base,bars:eligible}),actual=chartImage({...base,bars:[...eligible,late,...bars.slice(32).map(b=>({...b,closedAt:b.t+3600000-1,recordedAt:b.t+3600000-1}))]})
 eq(actual.svg,expected.svg);eq(actual.svg.includes('987654'),false);assertThrows(()=>chartImage({...base,bars:eligible},[id]),Error,'replay_snapshot_annotations')
})
