import {assertEquals as eq,assert} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {groupConfirmedLevels,chartStructureReview} from './chart-levels.ts'
import {structureDrawing,type StructureFinding} from './chart-structure.ts'
const t=1789041600000,step=60000
const pivot=(id:string,price:number,offset:number,window=2):StructureFinding=>({id,price,t:t+offset*step,confirmedAt:t+(offset+window+1)*step-1,knownAt:t+(offset+window+1)*step,kind:'high',label:'Confirmed swing high',definition:'fixture',window})
const bars=Array.from({length:70},(_,i)=>{const c=100+5*Math.sin(i*Math.PI/6)+i*.001;return {t:t+i*step,closedAt:t+(i+1)*step-1,recordedAt:t+(i+1)*step,o:c-.2,h:c+1,l:c-1,c,v:100}})
const options={at:t+80*step,intervalMs:step,window:2}
Deno.test('one source pivot at two windows is still one confirmation',()=>{const r=groupConfirmedLevels([pivot('short',110,5),pivot('wide',110,5,4)],100,4,2)[0];eq(r.distinctPivots,1);eq(r.tier,'Single pivot');eq(r.windows,[2,4]);eq(r.label,'Resistance zone');eq(r.distanceAtr,2.5)})
Deno.test('repeated levels expose exact member evidence rather than invented strength scores',()=>{const r=groupConfirmedLevels([pivot('a',110,5),pivot('b',110.5,12),pivot('wide',110,5,4)],100,4,2)[0];eq(r.tier,'Repeated across windows');eq(r.distinctPivots,2);eq(r.confirmations.length,3);eq(r.lower,110);eq(r.upper,110.5);eq(r.confirmedAt,t+15*step-1);eq('confidence' in r,false)})
Deno.test('transitive nearby pivots cannot inflate the declared maximum zone width',()=>{const r=groupConfirmedLevels([pivot('a',110,5),pivot('b',110.75,10),pivot('c',111.5,15)],100,4,2);eq(r.length,2);assert(r.every(z=>z.upper!-z.lower!<=1))})
Deno.test('zone role and distance use the nearest boundary and change with the actual last close',()=>{const p=[pivot('a',100,5),pivot('b',100.5,10)];eq(groupConfirmedLevels(p,101,4,2)[0].label,'Support zone');eq(groupConfirmedLevels(p,101,4,2)[0].distanceAtr,-.125);eq(groupConfirmedLevels(p,100.25,4,2)[0].label,'Zone at current close');eq(groupConfirmedLevels(p,100.25,4,2)[0].distanceAtr,0)})
Deno.test('confirmed OHLC fixtures produce tiered levels and missing bars reset active-zone coverage',()=>{const r=chartStructureReview(bars,options);assert(r.levels.length>=2);assert(r.levels.some(z=>z.distinctPivots>1));const disconnected=[...bars.slice(0,40),...bars.slice(60)];const gap=chartStructureReview(disconnected,options);eq(gap.levels.length,0);assert(gap.levelsReason?.includes('ATR'))})
Deno.test('future bars and delayed captures cannot leak into past tiers',()=>{for(const i of [20,30,40,55]){const at=bars[i].recordedAt;const full=chartStructureReview(bars,{...options,at,knownOnly:true}),prefix=chartStructureReview(bars.slice(0,i+1),{...options,at,knownOnly:true});eq(full.levels,prefix.levels)}const late=bars.map(b=>({...b,recordedAt:t+100*step}));eq(chartStructureReview(late,{...options,knownOnly:true}).levels,[])})
Deno.test('unknown close times and zero ATR produce no manufactured grouping width',()=>{eq(groupConfirmedLevels([pivot('a',100,5)],100,0,2),[]);eq(chartStructureReview(bars.map(b=>({...b,closedAt:undefined})),options).levels,[])})
Deno.test('kept zones preserve original time anchors, method and exact confirmation description',()=>{const z=groupConfirmedLevels([pivot('a',100,5),pivot('b',100.5,10)],105,4,2)[0],d=structureDrawing(z,'d204aaf9-ef74-4f93-a1c3-936d2c4be4f1','Synthetic OHLC');eq(d.tool,'rectangle');eq(d.anchors,[{t:t+5*step,price:100},{t:t+13*step-1,price:100.5}]);assert(d.text.includes('levels-1'));assert(d.text.includes('2 distinct source bars'));eq(structureDrawing(groupConfirmedLevels([pivot('a',100,5)],105,4,2)[0],d.id,'fixture').tool,'ray')})
