import {assertEquals as eq,assertRejects,assertThrows,assertStringIncludes as includes} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {makeChartCaptureProof,chartProofAsset} from './chart-capture-proof.ts'
import {buildChartSnapshot} from './chart-snapshot-service.ts'
import {projectSnapshotPrices,snapshotExportAllowed} from './chart-snapshot-prices.ts'
import {chartSourceShareAllowed,projectChartShare} from './chart-share-service.ts'
import {chartImage} from './chart-image.ts'
import {chartAlertConfig,chartAlertAssetAliases} from './chart-alert-service.ts'
const now=1789050000000,secret='comparison-tests-only-not-a-real-key',assets=[{asset:'market:coinmarketcap:1',label:'Bitcoin'},{asset:'market:coinmarketcap:1027',label:'Ethereum'}]
const env=(k:string)=>['CMC_ALLOW_HISTORICAL_RETENTION','INTEL_CHART_CMC_PRODUCT_SHARING','INTEL_CHART_COINGECKO_RETENTION'].includes(k)?'true':undefined
const fixture=async(providers=['coinmarketcap','coinmarketcap'])=>{
 const series=await Promise.all(assets.map(async(a,i)=>{const bars=[0,1,2].map(j=>({t:now-3000+j*1000,c:10*(i+1)+j,closedAt:now-2001+j*1000})),source={provider:providers[i],currency:'USD',timestampMeaning:'open' as const,intervalMs:1000,observedAt:now-1,servedAt:now,sourceUrl:'https://coinmarketcap.com/'};return {asset:a.asset,bars,proof:await makeChartCaptureProof(a.asset,bars,source,secret,now)}}))
 return {title:'BTC / ETH <script> comparison',layout:{schemaVersion:1,asset:assets[0].asset,range:{from:now-2001,to:now-1},studies:[],drawings:[],comparison:{assets,arrangement:'2x2',priceScale:'independent',period:'7D'}},capture:{series}}
}
Deno.test('each comparison asset preserves its independently verified source hash, clocks and original bars',async()=>{const input=await fixture(),s=await buildChartSnapshot(input,secret,env,now);eq(s.comparisonSeries.length,2);eq(s.bars,null);eq(s.comparisonSeries[1].bars[1].c,21);eq(s.comparisonSeries[1].bars[0].closedAt,now-2001);eq(s.comparisonSeries.map((c:any)=>c.sourceHash),input.capture.series.map(c=>c.proof.hash));eq(s.capturedAt,now);eq(snapshotExportAllowed(s,env,now),false);eq(chartSourceShareAllowed(s,env,now),true)})
Deno.test('missing, substituted, reordered and tampered captures cannot certify a saved comparison',async()=>{const input=await fixture();for(const series of [input.capture.series.slice(0,1),[...input.capture.series].reverse(),[input.capture.series[0],{...input.capture.series[0],asset:assets[1].asset}],[input.capture.series[0],{...input.capture.series[1],bars:[{t:now-2000,c:99999}]}]])await assertRejects(()=>buildChartSnapshot({...input,capture:{series}},secret,env,now))})
Deno.test('an expired proof on one asset rejects the new save even while another remains valid',async()=>{const input=await fixture();input.capture.series[1].proof=await makeChartCaptureProof(assets[1].asset,input.capture.series[1].bars,input.capture.series[1].proof.source,secret,now-3600000);await assertRejects(()=>buildChartSnapshot(input,secret,env,now),Error,'expired_or_invalid')})
Deno.test('mixed permissions preserve permitted prices independently and block an unsupported external share',async()=>{const s=await buildChartSnapshot(await fixture(['coinmarketcap','coingecko']),secret,k=>k.startsWith('INTEL_CHART_COINGECKO')?undefined:env(k),now);eq(s.comparisonSeries[0].bars.length,3);eq(s.comparisonSeries[1].bars,null);eq(s.comparisonSeries[1].sourceHash.length,64);eq(chartSourceShareAllowed(s,env,now),false);eq(projectSnapshotPrices(s,env,now).availability.availableSources,1)})
Deno.test('one source expiry or policy revocation cannot remove another source or restore missing prices',async()=>{const s=await buildChartSnapshot(await fixture(['coinmarketcap','coingecko']),secret,env,now);s.comparisonSeries[0].policy.retainUntil=now+1000;const original=JSON.stringify(s),p=projectSnapshotPrices(s,env,now+1000);eq(p.state.comparisonSeries[0].bars,null);eq(p.state.comparisonSeries[1].bars.length,3);eq(p.state.hash,s.hash);eq(p.availability.availableSources,1);eq(JSON.stringify(s),original);eq(projectSnapshotPrices(s,k=>k.startsWith('CMC_')?undefined:env(k),now).state.comparisonSeries[0].bars,null)})
Deno.test('shared comparison projections include every source and exclude arbitrary capture-private fields',async()=>{const s=await buildChartSnapshot(await fixture(),secret,env,now);s.comparisonSeries[1].userNotes='Ambient private trade words';const v=await projectChartShare({snapshot:s,audience:'org',drawingIds:[],expiresAt:new Date(now+10000).toISOString()},env,now);eq(v.comparisonSeries.length,2);eq(v.comparisonSeries[1].sourceHash,s.comparisonSeries[1].sourceHash);eq(JSON.stringify(v).includes('Ambient private'),false);eq(v.hash===s.hash,false);await assertRejects(()=>projectChartShare({snapshot:s,audience:'org'},()=>undefined,now),Error,'source_unavailable')})
Deno.test('static comparison exports preserve arrangement, each source and shared close-time baseline',async()=>{const s=await buildChartSnapshot(await fixture(),secret,env,now);for(const arrangement of ['overlay','2x2','1x4']){const r=chartImage({...s,layout:{...s.layout,comparison:{...s.layout.comparison,arrangement}}});includes(r.svg,'Bitcoin');includes(r.svg,'Ethereum');includes(r.svg,s.comparisonSeries[1].sourceHash);eq(/NaN|Infinity|<script>/.test(r.svg),false);includes(r.svg,'&lt;script&gt;');eq(r.pngAvailable,true);if(arrangement==='overlay')includes(r.svg,'Common baseline:')}})
Deno.test('an unaligned return export is explicit while independent prices remain exportable',async()=>{const s=await buildChartSnapshot(await fixture(),secret,env,now);s.comparisonSeries[1].bars=s.comparisonSeries[1].bars.map((b:any)=>({...b,closedAt:b.closedAt-100}));assertThrows(()=>chartImage({...s,layout:{...s.layout,comparison:{...s.layout.comparison,arrangement:'overlay'}}}),Error,'export_unaligned');eq(chartImage(s).format,'svg')})
Deno.test('canonical EVM casing agrees across proof, alert saving and marker history without lowercasing Solana',()=>{const mixed='eip155:8453:0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',lower=mixed.toLowerCase();eq(chartProofAsset(mixed),lower);eq(chartAlertAssetAliases(mixed).includes(lower),true);eq(chartAlertConfig({asset:mixed,threshold_usd:1,direction:'above',title:'USDC',note:''}).asset,lower);const sol='solana:So11111111111111111111111111111111111111112';eq(chartProofAsset(sol),sol)})
