import {assertEquals as eq,assertThrows} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {cmcChartPlan,aggregateOhlcv,cmcOhlcvBars,loadCmcChart,nativeCmcId,cmcFallbackCoverage} from './cmc-chart.ts'
import {cmcParams,estimateCmcCredits} from '../market-assets/cmc-capabilities.ts'
import {chartSeriesResponse} from './chart-series-contract.ts'
const h=3600000,d=24*h,t=Date.parse('2026-09-01T00:00:00Z'),now=Date.parse('2026-09-10T16:30:00Z')
const bar=(i:number)=>({t:t+i*h,o:10+i,h:13+i,l:9+i,c:12+i,v:i+1,closedAt:t+(i+1)*h-1,recordedAt:now})
Deno.test('publication delay reuses one cache key across the clock hour boundary',()=>{eq(cmcChartPlan('1027','7D','4H',Date.parse('2026-09-10T20:59Z')).pages,cmcChartPlan('1027','7D','4H',Date.parse('2026-09-10T21:06Z')).pages)})
Deno.test('fallback describes the actual CMC failure without inventing volume or entitlement',()=>{eq(cmcFallbackCoverage({sourceState:'refreshing',sourceReason:'refreshing'},'4H').includes('shared refresh is in progress'),true);eq(cmcFallbackCoverage({sourceReason:'feature_budget_exceeded'},'4H').includes('history credit allowance'),true);eq(cmcFallbackCoverage(null,'4H').includes('verified CMC identity'),true)})
Deno.test('all users within the same publication hour share bounded request parameters',()=>{eq(cmcChartPlan('1','7D','1H',now).pages,cmcChartPlan('1','7D','1H',now+60000).pages);for(const range of ['24H','7D','1M','1Y'])for(const interval of ['1H','4H','1D','1W']){const plan=cmcChartPlan('1',range,interval,now);eq(plan.pages.length<=4,true);for(const p of plan.pages){const valid=cmcParams('ohlcv',p);eq(Number(valid.count)<=241,true);eq(estimateCmcCredits('ohlcv',valid)<=3,true)}}})
Deno.test('Startup intraday stops at 30 days and never silently changes the requested interval',()=>{const plan=cmcChartPlan('1','1Y','4H',now);eq(plan.limited,true);eq(plan.step,4*h);eq(plan.base,h);eq(plan.pages.length,3);eq(cmcChartPlan('1','1M','auto',now).base,d)})
Deno.test('only OHLCV supports bounded hourly periods; sampling cannot impersonate aggregation',()=>{eq(cmcParams('ohlcv',{id:'1',time_period:'hourly',interval:'hourly',count:24}).interval,'hourly');assertThrows(()=>cmcParams('ohlcv',{id:'1',time_period:'hourly',interval:'4h'}));assertThrows(()=>cmcParams('history',{id:'1',interval:'hourly'}));assertThrows(()=>cmcParams('ohlcv',{id:'1',time_period:'hourly',interval:'hourly',count:2,time_start:'2026-09-01',time_end:'2026-09-03'}))})
Deno.test('four-hour candles preserve actual open high low close and sum genuine volume',()=>{const r=aggregateOhlcv([bar(3),bar(0),bar(2),bar(1)],h,4*h,now);eq(r.bars,[{t,o:10,h:16,l:9,c:15,v:10,closedAt:t+4*h-1,recordedAt:now}]);eq(r.incomplete,0)})
Deno.test('CMC overlapping hourly volume uses the final reading instead of adding repeated flow',()=>{const rows=[bar(0),bar(1),bar(2),bar(3)].map(b=>({...b,volumeKind:'snapshot' as const,volumeUnit:'USD' as const}));const result=aggregateOhlcv(rows,h,4*h,now).bars[0];eq(result.v,4);eq(result.volumeKind,'snapshot');eq(result.volumeUnit,'USD');eq(result.o,10);eq(result.h,16);eq(result.l,9);eq(result.c,15);eq(aggregateOhlcv([...rows.slice(0,3),{...rows[3],v:null}],h,4*h,now).bars[0].v,null)})
Deno.test('missing, duplicate and unfinished hours never create a full candle',()=>{for(const rows of [[bar(0),bar(2),bar(3)],[bar(0),bar(1),bar(1),bar(3)]])eq(aggregateOhlcv(rows,h,4*h,now).bars,[]);eq(aggregateOhlcv([bar(0),bar(1),bar(2),bar(3)],h,4*h,t+3*h).bars,[]);eq(aggregateOhlcv([bar(0),bar(1),{...bar(2),v:null},bar(3)],h,4*h,now).bars[0].v,null)})
Deno.test('weekly aggregation starts Monday and omits partial weeks',()=>{const monday=Date.parse('2026-08-31T00:00:00Z');const rows=Array.from({length:7},(_,i)=>({...bar(i),t:monday+i*d,closedAt:monday+(i+1)*d-1}));eq(aggregateOhlcv(rows,d,7*d,now).bars[0].t,monday);eq(aggregateOhlcv(rows.slice(1),d,7*d,now).bars,[])})
Deno.test('CMC ID maps and single-object schemas retain exact identity, source clocks and missing volume',()=>{const point={time_open:new Date(t).toISOString(),time_close:new Date(t+h-1).toISOString(),quote:{USD:{open:10,high:13,low:9,close:12}}};const row={id:1,quotes:[point]};const a=cmcOhlcvBars({data:{'1':row}},'1',now,h);eq(a,cmcOhlcvBars({data:row},'1',now,h));eq(a[0].v,null);eq(a[0].closedAt,t+h-1);eq(cmcOhlcvBars({data:row},'2',now,h),[]);eq(cmcOhlcvBars({data:{...row,quotes:[{...point,time_close:new Date(t+2*h).toISOString()}]}},'1',now,h),[])})
Deno.test('a denied history page stops fan-out and explains coverage',async()=>{let calls=0;const result=await loadCmcChart({},'1','1M','4H',now,async()=>{calls++;return {payload:null,state:'unsupported',reason:'insufficient_entitlement',provenance:{provider:'coinmarketcap',observedAt:null,fetchedAt:null,expiresAt:null,sourceUrl:'https://coinmarketcap.com/'}}});eq(calls,1);eq(result.candles,[]);eq(result.sourceReason,'insufficient_entitlement')})
Deno.test('verified native ID mappings do not use governance symbols',()=>{eq(nativeCmcId('bitcoin'),'1');eq(nativeCmcId('arbitrum'),'1027');eq(nativeCmcId('unknown'),null)})
Deno.test('open timestamps and known candle duration survive source normalization and sparse bars',()=>{const r=chartSeriesResponse({source:'coinmarketcap',timestampMeaning:'open',barIntervalMs:h,volumeUnit:'USD',candles:[bar(0),bar(3)]},now);eq(r.source.intervalMs,h);eq(r.source.timestampMeaning,'open');eq(r.candles[0].closedAt,t+h-1);eq(r.source.volumeUnit,'USD')})
