import {assertEquals as eq} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {interpretStressRules,thesisStress,stressSensitivity} from './investigation-calculations.ts'
const at=1789050000000,subject='market:coinmarketcap:1',rule={id:'rule',metric:'price_move',description:'Exit if the 24-hour move exceeds 10%',comparator:'gt',threshold:10,rule_kind:'invalidation'}
const observation=(period:number,value:number)=>({id:String(period),subject,metric:'price_change',value,unit:'%',provider:'example',sourceRef:'example:price',observedAt:new Date(at-1000).toISOString(),recordedAt:new Date(at-900).toISOString(),expiresAt:new Date(at+1000).toISOString(),periodSeconds:period})
Deno.test('ambiguous legacy rules do not guess whether a threshold is USD, percent or another window',()=>{const rows=thesisStress(interpretStressRules([rule]),[observation(86400,15)],subject,{rule:20},at);eq(rows[0].currentlyMet,null);eq(rows[0].scenarioMet,null);eq(stressSensitivity(rows[0]),null);eq(rows[0].rule.label,rule.description)})
Deno.test('explicit scenario basis matches exact units and periods and preserves strict comparator behavior',()=>{const rules=interpretStressRules([rule],{rule:'price_24h'}),row=thesisStress(rules,[observation(3600,90),observation(86400,10)],subject,{rule:10.01},at)[0];eq(row.current,10);eq(row.currentlyMet,false);eq(row.scenarioMet,true);eq(row.observation?.periodSeconds,86400);eq(rule.metric,'price_move');eq(stressSensitivity(row)?.points.length,21)})
Deno.test('two conditions on the same metric keep distinct scenario inputs',()=>{const rules=[{...rule,id:'one',metric:'price',unit:'USD',threshold:100},{...rule,id:'two',metric:'price',unit:'USD',threshold:100}];const rows=thesisStress(rules,[],subject,{one:80,two:120},at);eq(rows.map(r=>r.scenarioMet),[false,true])})
Deno.test('a source with a different period remains missing and is not substituted',()=>{const row=thesisStress(interpretStressRules([rule],{rule:'price_7d'}),[observation(86400,15)],subject,{},at)[0];eq(row.current,null);eq(row.currentlyMet,null)})
Deno.test('qualitative conditions have no invented numerical sensitivity',()=>{const row=thesisStress([{...rule,metric:'manual',threshold:null}],[],subject,{},at)[0];eq(stressSensitivity(row),null)})
