import {assertEquals as eq,assertRejects} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {readMarketAlertEvidence,marketAlertFailure} from './market-alert-evidence.ts'
const now=Date.parse('2026-09-11T12:00:00Z'),iso=(offset:number)=>new Date(now+offset).toISOString(),address='0x'+'a'.repeat(40),subject=`eip155:8453:${address}`,rule={trigger_type:'liquidity_drop',entity:{canonical_ref_key:subject,display_symbol:'ETH'}}
function db(row:any,error:any=null){const calls:any[]=[];const q:any={maybeSingle:async()=>({data:row,error}),limit:async()=>({data:row,error})};for(const method of ['select','eq','or','gt','gte','lte','order'])q[method]=(...args:any[])=>{calls.push([method,...args]);return q};return {calls,from:(table:string)=>{calls.push(['from',table]);return q}}}
const cached={chain:'base',token_address:address,normalized_response:{liquidity:0,price_change_24h_pct:0},fetched_at:iso(-60000),expires_at:iso(60000)}
Deno.test('exact contract cache preserves zero and distinguishes capture time from unknown provider time',async()=>{const database=db(cached),r=await readMarketAlertEvidence(database,rule,now);eq(r.observation.value,0);eq(r.observation.observedAt,null);eq(r.observation.sampleAt,cached.fetched_at);eq(r.observation.clockBasis,'cache_capture');eq(database.calls.some(c=>c[0]==='eq'&&c[1]==='token_address'&&c[2]===address),true)})
Deno.test('wrong identity, expired, future and missing cached inputs are explicit failures',async()=>{for(const patch of [{chain:'ethereum'},{token_address:'other'},{expires_at:iso(0)},{fetched_at:iso(1)}])await assertRejects(()=>readMarketAlertEvidence(db({...cached,...patch}),rule,now));await assertRejects(()=>readMarketAlertEvidence(db(cached,{message:'private detail'}),rule,now),Error,'source_read_failed');await assertRejects(()=>readMarketAlertEvidence(db(null),rule,now),Error,'coverage_unavailable')})
Deno.test('native CMC price-change evidence uses the original provider timestamp and rolling 24-hour window',async()=>{const database=db([{observation:{id:'cmc-zero',subject:'market:coinmarketcap:1',metric:'price_change',value:0,unit:'%',periodSeconds:86400,provider:'coinmarketcap',sourceRef:'coinmarketcap:/v3/cryptocurrency/listings/latest:{}',observedAt:iso(-120000),recordedAt:iso(-60000),expiresAt:iso(60000),aiAllowed:true}}]);const r=await readMarketAlertEvidence(database,{trigger_type:'price_move',entity:{canonical_ref_key:'native:bitcoin'}},now);eq(r.observation.value,0);eq(r.observation.providerSubject,'market:coinmarketcap:1');eq(r.observation.clockBasis,'provider_observation');eq(r.observation.sampleAt,iso(-120000))})
Deno.test('a ticker or unrelated native hint cannot substitute for a contract',async()=>{await assertRejects(()=>readMarketAlertEvidence(db(cached),{...rule,entity:{canonical_ref_key:'unknown',display_symbol:'ETH',provider_ids:{coinmarketcap:'1027'}}},now),Error,'canonical_identity');await assertRejects(()=>readMarketAlertEvidence(db(cached),{...rule,entity:{canonical_ref_key:'native:bitcoin'}},now),Error,'metric_coverage')})
Deno.test('untrusted database details cannot leak into a recorded status message',()=>{eq(marketAlertFailure(Error('secret database detail')).status,'evaluation_failed');eq(JSON.stringify(marketAlertFailure(Error('secret database detail'))).includes('secret'),false)})
