import {assertEquals as eq} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {evaluateMarketAlerts} from './market-alert-evaluator.ts'
import type {readMarketAlertEvidence} from './market-alert-evidence.ts'
const evidence:Awaited<ReturnType<typeof readMarketAlertEvidence>>={metric:'price_change_24h_pct',unit:'%',overview:{price:100,price_change_24h_pct:0,symbol:'BTC'},observation:{id:'obs',subject:'native:bitcoin',provider:'coinmarketcap',sourceRef:'retained:obs',providerSubject:'market:coinmarketcap:1',value:0,unit:'%',periodSeconds:86400,observedAt:'2026-09-11T12:00:00Z',recordedAt:'2026-09-11T12:00:01Z',expiresAt:'2026-09-11T12:04:01Z',sampleAt:'2026-09-11T12:00:00Z',clockBasis:'provider_observation',coverage:'Controlled retained-source fixture'}}
const rule={id:'one',org_id:'org',chart_revision:2,trigger_type:'price_move',entity:{canonical_ref_key:'native:bitcoin'}}
function database(rules:any[],options:any={}){const calls:any[]=[];const query:any={then:(ok:any)=>Promise.resolve({data:rules,error:options.readError}).then(ok)};for(const method of ['select','eq','in','order','limit','update'])query[method]=(...args:any[])=>{calls.push([method,...args]);return query};return {calls,from:()=>query,rpc:async(name:string,args:any)=>{calls.push([name,args]);return name==='intel_record_alert_evaluation'?{data:true}:{data:options.state===null?null:{state:options.state||'baseline',eventId:'event'},error:options.writeError}}}}
Deno.test('two owners share a bounded public read but commit separate authorized rule versions',async()=>{const db=database([rule,{...rule,id:'two'}],{state:'fired'});let reads=0,events=0;const r=await evaluateMarketAlerts(db,async()=>{events++},async()=>{reads++;return evidence});eq(reads,1);eq(events,2);eq(r.fired,2);eq(db.calls.filter(c=>c[0]==='intel_record_market_alert').map(c=>c[1].p_revision),[2,2]);eq(db.calls.some(c=>c[0]==='limit'&&c[1]===400),true)})
Deno.test('native assets are evaluated without a contract address; failures are persisted',async()=>{for(const reason of ['alert_fresh_source_unavailable','secret upstream failure']){const db=database([rule]);const result=await evaluateMarketAlerts(db,async()=>{},async()=>{throw Error(reason)});eq(result.checked,1);eq(result.unavailable+(result.failed>0?1:0),1);const state=db.calls.find(c=>c[0]==='intel_record_alert_evaluation')[1].p_state;eq(JSON.stringify(state).includes('secret'),false)}})
Deno.test('rule loading and atomic writes fail visibly, without fake empty success',async()=>{eq((await evaluateMarketAlerts(database([],{readError:{}}),async()=>{})).failed,1);const r=await evaluateMarketAlerts(database([rule],{writeError:{}}),async()=>{},async()=>evidence);eq(r.failed,1);eq(r.fired,0)})
Deno.test('repeated source advances scheduling but preserves receipt; changed rules are not overwritten',async()=>{for(const state of ['same_observation','changed']){const db=database([rule],{state});await evaluateMarketAlerts(db,async()=>{},async()=>evidence);eq(db.calls.some(c=>c[0]==='update'),state==='same_observation');eq(db.calls.some(c=>c[0]==='intel_record_alert_evaluation'),false)}})
