import {assertEquals as eq} from 'https://deno.land/std@0.224.0/assert/mod.ts'
import {participationContract,participationRecord,reportedHolderCount,reportedSnapshotHolderCount,readParticipation} from './participation-read.ts'
import {participationQuality} from './investigation-calculations.ts'
const now=1789041600000,row={id:'a',computed_at:new Date(now-1000).toISOString(),top1_pct:80,top10_pct:20,gini:.4,holder_count:20,source_providers:['birdeye'],score_version:1}
Deno.test('sample-relative largest holder does not invalidate the provider top-ten percentage',()=>{const r=participationQuality(participationRecord(row,'asset'),null,now);eq(r.top1Percent,null);eq(r.top10Percent,20);eq(r.inconsistent,false);eq(participationRecord(row,'asset').sampledTop1Percent,80)})
Deno.test('legacy partial-list count is withheld; version two permits only reported integer totals',()=>{eq(participationRecord(row,'asset').holderCount,null);eq(participationRecord({...row,score_version:2,holder_count:450},'asset').holderCount,450);for(const v of [null,undefined,'',true,-1,2.5,Infinity])eq(reportedHolderCount(v),null);eq(reportedHolderCount(0),0)})
Deno.test('contract aliases share an exact read identity; native and ticker names are rejected',()=>{const a='0x'+'a'.repeat(40);eq(participationContract(`eip155:42161/erc20:${a}`),{chain:'arbitrum',address:a});eq(participationContract(`eip155:42161:${a.toUpperCase()}`),{chain:'arbitrum',address:a});eq(participationContract('ARB'),null);eq(participationContract('native:arbitrum'),null)})
Deno.test('participation reads bound exact contract and time before returning history',async()=>{const calls:any[]=[];const q:any={};for(const name of ['select','eq','ilike','gte','lte','order','limit'])q[name]=(...v:any[])=>{calls.push([name,...v]);return q};q.then=(ok:any)=>Promise.resolve(ok({data:[row,{...row,computed_at:new Date(now+1).toISOString()}]}));const a='0x'+'a'.repeat(40);const result=await readParticipation({from:()=>q},`eip155:1:${a}`,now);eq(result.length,1);eq(calls.some(c=>c[0]==='ilike'&&c[1]==='token_address'&&c[2]===a),true);eq(calls.some(c=>c[0]==='limit'&&c[1]===100),true);eq(calls.some(c=>c[0]==='lte'&&c[1]==='computed_at'),true)})

Deno.test('old raw totals cannot be laundered into verified counts by a new score writer',()=>{eq(reportedSnapshotHolderCount({total:20,sample:[1,2]}),null);eq(reportedSnapshotHolderCount({total:450,holder_count_basis:'provider_reported_v2'}),450);eq(reportedSnapshotHolderCount({total:null,holder_count_basis:'provider_reported_v2'}),null);eq(participationRecord({...row,score_version:3},'asset').holderCount,null)})
Deno.test('matching provider and scoring version do not imply matching holder populations',()=>{const current=participationRecord({...row,score_version:2},'asset'),prior=participationRecord({...row,score_version:2,computed_at:new Date(now-86400000).toISOString()},'asset');eq(participationQuality(current,prior,now).comparable,false)})
