import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import TokenChart, { MarkerDetails } from '../product/src/intel/components/TokenChart.jsx'
import { candles as fixtureCandles } from './fixtures.mjs'
import { ASSET_KEY, heldQuantity, validMovement } from './notebook.mjs'
import { ohlcvBars } from './chart-data.mjs'
import './style.css'
import '../product/src/intel/workspace.css'
i18n.use(initReactI18next).init({lng:'en',fallbackLng:'en',defaultNS:'intel',resources:{en:{intel:{}}},interpolation:{escapeValue:false}})
const money=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:Number(v)>1000000?'compact':'standard',maximumFractionDigits:2}).format(Number(v))
const value=(row,...names)=>names.map(n=>row?.[n]??row?.quote?.[n]??row?.exchangeReportedQuote?.[n]).find(v=>v!=null)
const text=v=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v)
const STORAGE='investor-intel-local-demo-v1'
async function research(capability,params={},retry=true){const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({capability,params})});const body=await r.json();if(!r.ok)throw Error(body.error||'Research is unavailable');if(retry&&body.reason?.startsWith('Shared local rate limit')){await new Promise(resolve=>setTimeout(resolve,2200));return research(capability,params,false)}return body}
const t=(key,options)=>options?.defaultValue||key
function Evidence({result}){return result?<p className="evidence"><span className={result.state==='fresh'?'dot':'dot amber'}/>{result.fixture?'Synthetic example':result.provenance?.provider==='coinmarketcap'?'CoinMarketCap':'Unknown source'} · {result.state}{result.reason?` · ${result.reason}`:''}{result.provenance?.observedAt?` · observed ${new Date(result.provenance.observedAt).toLocaleString()}`:' · observation time unavailable'}{!result.fixture&&<a href="https://coinmarketcap.com" target="_blank" rel="noreferrer">Data provided by CoinMarketCap.com</a>}</p>:null}
function initialJournal(){const now=Date.now();return [{id:'example-thesis',t:now-5*86400000,type:'thesis_created',group:'thesis',label:'Thesis opened',actorKind:'user',title:'Ethereum: watch activity, not just price',textSnapshot:{rationale:'Example thesis: look for sustained network demand alongside market participation.',invalidation:'Review if market participation weakens for several observations.'}},{id:'example-deposit',t:now-4*86400000,type:'deposit',group:'portfolio',label:'Example deposit',quantity:1.25,direction:'in',status:'success',source:'Synthetic manual ledger',notes:'Example funding event; no on-chain transaction was performed.',executionPrice:null},{id:'example-edit',t:now-86400000,type:'thesis_edited',group:'thesis',label:'Research updated',actorKind:'user',title:'Participation remains the key test',textSnapshot:{rationale:'Example update: wait for corroborating activity evidence before strengthening conviction.'},changes:{conviction:{before:50,after:55}}}]}
function App(){
  const [demoState,setDemoState]=useState('populated'),[theme,setTheme]=useState(()=>localStorage.getItem('intel-demo-theme')||'dark')
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('intel-demo-theme',theme)},[theme])
  const [tab,setTab]=useState('asset'),[status,setStatus]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [journal,setJournal]=useState(()=>{try{return JSON.parse(localStorage.getItem(STORAGE))||initialJournal()}catch{return initialJournal()}})
  const [thesis,setThesis]=useState('Participation remains the key test'),[note,setNote]=useState(''),[quantity,setQuantity]=useState('0.25'),[action,setAction]=useState('thesis_edited'),[details,setDetails]=useState(null),[alert,setAlert]=useState(''),[threshold,setThreshold]=useState('3600')
  const [quoteRaw,setQuote]=useState(null),[historyRaw,setHistory]=useState(null),[rwasRaw,setRwas]=useState(null),[rwaRaw,setRwa]=useState(null),[rwaQuotesRaw,setRwaQuotes]=useState(null),[issuersRaw,setIssuers]=useState(null),[issuerRaw,setIssuer]=useState(null),[exchangesRaw,setExchanges]=useState(null),[pairsRaw,setPairs]=useState(null),[liquidationsRaw,setLiquidations]=useState(null)
  useEffect(()=>{fetch('/api/status').then(r=>r.json()).then(setStatus).catch(()=>setError('Start the local API to use the demo.'))},[])
  useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify(journal))},[journal])
  async function run(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
  useEffect(()=>{if(!status)return;run(async()=>{if(tab==='asset'&&!quote){setQuote(await research('quotes',{id:1027}));setHistory(await research('ohlcv',{id:1027,count:90,interval:'daily',time_period:'daily'}))}if(tab==='rwa'&&!rwas)setRwas(await research('rwaList',{limit:10}));if(tab==='structure'&&!exchanges)setExchanges(await research('derivativeExchanges',{limit:10}))})},[tab,status])
  const fixture=status?.mode!=='live'
  const displayResult=result=>!fixture||!result?result:demoState==='stale'?{...result,state:'stale',provenance:{...result.provenance,observedAt:new Date(Date.now()-7200000).toISOString()}}:['empty','loading','error'].includes(demoState)?{...result,state:demoState==='error'?'unavailable':demoState,data:{rows:[],total:0,hasMore:false},reason:demoState==='error'?'Simulated fixture provider error':demoState==='empty'?'No market snapshot available':null}:result
  const [quote,history,rwas,rwa,rwaQuotes,issuers,issuer,exchanges,pairs,liquidations]=[quoteRaw,historyRaw,rwasRaw,rwaRaw,rwaQuotesRaw,issuersRaw,issuerRaw,exchangesRaw,pairsRaw,liquidationsRaw].map(displayResult)
  const graph=fixture?(['populated','stale'].includes(demoState)?fixtureCandles():[]):ohlcvBars(history)
  const price=value(quote?.data?.rows?.[0],'price')
  const held=heldQuantity(journal),movement=['deposit','withdrawal','swap'].includes(action),movementDirection=action==='withdrawal'?'out':'in'
  const movementValid=!movement||validMovement(quantity,movementDirection,held)
  function save(){if(!note.trim()||!movementValid)return;const portfolio=['deposit','withdrawal','swap'].includes(action);const recordedAt=Date.now();const record={id:crypto.randomUUID(),t:recordedAt,recordedAt,type:action,group:portfolio?'portfolio':'thesis',label:portfolio?`Manual ${action}`:action==='thesis_reviewed'?'Thesis reviewed':'Thesis edited',actorKind:'user',title:thesis,textSnapshot:portfolio?null:{rationale:note},notes:portfolio?note:null,status:portfolio?'success':null,quantity:portfolio?Number(quantity):null,direction:portfolio?(action==='withdrawal'?'out':'in'):null,source:portfolio?'Synthetic manual ledger':'Local research notebook',assetKey:ASSET_KEY,tokenSymbol:'ETH',chain:'ethereum',executionPrice:null};setJournal(old=>[...old,record]);setNote('')}
  async function selectRwa(row){await run(async()=>{setRwa(await research('rwaInfo',{rwa_id:row.rwa_id}));setRwaQuotes(await research('rwaQuotes',{rwa_id:row.rwa_id}))})}
  return <div className="shell">
    <aside><a className="brand" href="#" onClick={e=>e.preventDefault()}><span>i</span> Investor Intel</a><div className="eyebrow nav-title">RESEARCH WORKSPACE</div><nav>{[['asset','Asset notebook'],['rwa','Real-world assets'],['structure','Market structure']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setDetails(null)}}>{label}<i>↗</i></button>)}</nav><div className="sidebar-note"><div className="eyebrow">PRIVATE DEMONSTRATION</div><p>Your thesis and activity stay in this browser. Market requests use the local server.</p><a href="https://coinmarketcap.com/api/" target="_blank" rel="noreferrer">Built with CoinMarketCap ↗</a></div></aside>
    <main><header><span className="eyebrow">RESEARCH / {tab==='asset'?'ETHEREUM':tab==='rwa'?'TOKENIZED MARKETS':'DERIVATIVES'}</span><div className="demo-controls">{fixture&&<label>Fixture state<select aria-label="Fixture state" value={demoState} onChange={e=>setDemoState(e.target.value)}>{['populated','loading','empty','stale','error'].map(state=><option key={state} value={state}>{state}</option>)}</select></label>}<button className="secondary" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'Light theme':'Dark theme'}</button><span className="mode">{fixture?'● FIXTURE MODE':'● LIVE CMC MODE'}</span></div></header>
      <div className="mode-banner">{fixture?'All market values, issuers and activity in this demonstration are synthetic. No API key or external calls are required.':'Market data comes from your server-side CMC key. Personal research and portfolio events are editable local examples.'}</div>
      {error&&<div className="error" role="alert">{error}</div>}{(busy||(fixture&&demoState==='loading'))&&<div className="loading" role="status">Loading shared research…</div>}
      {fixture&&demoState==='empty'&&<p className="state-note" role="status">Empty market snapshot. Personal research and recorded holdings remain available.</p>}{fixture&&demoState==='error'&&<p className="error" role="alert">Simulated fixture provider error. No external request failed.</p>}{fixture&&demoState==='stale'&&<p className="state-note" role="status">Stale fixture snapshot shown with an older observation time.</p>}
      {tab==='asset'&&<><div className="page-title"><div><div className="eyebrow">ASSET NOTEBOOK</div><h1>Ethereum research</h1><p>Read market context alongside what you actually thought and did.</p></div><div className="asset-quote"><span>ETHEREUM / ETH</span><strong>{money(price)}</strong><small>{fixture?'Synthetic example quote':'Latest available CMC quote'}</small></div></div>
        <section className="position" aria-label="Your example position"><div><div className="eyebrow">YOUR POSITION / SYNTHETIC PORTFOLIO</div><h2>{held.toLocaleString(undefined,{maximumFractionDigits:6})} ETH</h2><p>Recorded from {journal.filter(r=>r.group==='portfolio').length} local activity events</p></div><div><span>Illustrative market value</span><strong>{price==null?'Unavailable':money(held*price)}</strong><small>{fixture?'Synthetic holdings × synthetic quote':'Synthetic holdings × live CMC quote'}</small></div><div><span>Cost basis / P&amp;L</span><strong>Unavailable</strong><small>Execution price evidence was not supplied</small></div><div className="position-source"><span>Ethereum · Native ETH</span><code>{ASSET_KEY}</code><small>No wallet is connected; no transaction was executed.</small></div></section>
        <div className="workbench"><section className="panel chart-panel"><div className="section-title"><h2>Market & personal history</h2><span>ETH · USD</span></div><div className="intel-root demo-chart"><TokenChart priceCoverage={{state:history?.state,coverage:fixture?'Synthetic hourly OHLCV; no live market observation.':history?.reason||'CMC daily OHLCV; missing periods stay empty.',chartSource:{provider:fixture?'Synthetic example':'coinmarketcap',currency:'USD',intervalMs:fixture?3600000:86400000,timestampMeaning:'close',observedAt:graph.at(-1)?.t??null,volumeMethod:fixture?'Synthetic USD volume':'CMC aggregate USD volume'},provenance:history?.provenance}} timeWindow={{from:Date.now()-(fixture?7:90)*86400000,to:Date.now()}} candles={graph} markers={journal} assetKey={ASSET_KEY} defaultRange={fixture?'7D':'3M'} showDensityToggles keyLevels={alert?[{price:Number(threshold),label:'Local alert threshold'}]:[]}/></div><Evidence result={history||quote}/></section>
        <details className="panel thesis-panel"><summary>Record thesis or activity</summary><div className="demo-notebook-form"><div className="eyebrow">YOUR RESEARCH</div><h2>Record your assessment</h2><label>Thesis title<input value={thesis} onChange={e=>setThesis(e.target.value)}/></label><label>Record type<select value={action} onChange={e=>setAction(e.target.value)}><option value="thesis_edited">Thesis edit</option><option value="thesis_reviewed">Thesis review</option><option value="deposit">Manual deposit</option><option value="withdrawal">Manual withdrawal</option><option value="swap">Manual swap</option></select></label>{['deposit','withdrawal','swap'].includes(action)&&<label>Quantity (ETH)<input type="number" min="0.000001" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>}<label>Original note<textarea rows="5" placeholder="What changed in your assessment?" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={!note.trim()||!movementValid} onClick={save}>Save to history <span>↗</span></button><p className="fine">Every save appends an original event. Historical notes stay intact. Manual movements have no invented execution price.</p></div></details></div>
        <div className="below-grid"><section className="panel"><div className="section-title"><h2>Research ledger</h2><span>{journal.length} records</span></div>{journal.slice().reverse().slice(0,5).map(record=><button className="ledger-row" key={record.id} onClick={()=>setDetails(record)}><time>{new Date(record.t).toLocaleDateString()}</time><strong>{record.label}</strong><span>{record.group==='portfolio'?`${record.direction==='out'?'−':'+'}${record.quantity} ETH · Synthetic manual ledger`:record.title}</span><b>↗</b></button>)}</section><section className="panel"><div className="eyebrow">DETERMINISTIC CHECK</div><h2>Set a price observation.</h2><label>Observe when ETH is above (USD)<input type="number" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><button className="secondary" onClick={()=>setAlert(price==null?'No usable price to evaluate.':Number(price)>Number(threshold)?'Condition met in the latest displayed observation.':'Condition has not been met in the latest displayed observation.')}>Evaluate displayed quote</button>{alert&&<p role="status">{alert}</p>}<p className="fine">Local observation only. No trading, background notifications or automation.</p></section></div>
      </>}
      {tab==='rwa'&&<><div className="page-title"><div><div className="eyebrow">REAL-WORLD ASSETS</div><h1>Tokenized instruments</h1><p>Separate the underlying asset, its tokens and the issuer behind them.</p></div></div><section className="panel"><div className="section-title"><h2>Tokenized instruments</h2><button className="secondary" onClick={()=>run(async()=>setIssuers(await research('issuers',{limit:10})))}>Explore issuers ↗</button></div><table><thead><tr><th>Instrument</th><th>Asset class</th><th>Tokenized price</th><th>Tokenized value</th><th/></tr></thead><tbody>{(rwas?.data?.rows||[]).map(row=><tr key={row.rwa_id}><td><strong>{row.name||row.rwa_name||row.symbol}</strong><small>{row.symbol} · RWA {row.rwa_id}</small></td><td>{text(row.asset_type)}</td><td>{money(value(row,'average_tokenized_price'))}</td><td>{money(value(row,'tokenized_market_cap'))}</td><td><button onClick={()=>selectRwa(row)}>Investigate ↗</button></td></tr>)}</tbody></table><Evidence result={rwas}/></section>
        <div className="below-grid"><section className="panel"><div className="eyebrow">INSTRUMENT EVIDENCE</div><h2>{rwa?.data?.rows?.[0]?.name||rwa?.data?.rows?.[0]?.rwa_name||'Select an instrument'}</h2>{rwa?<><p>{rwa.data.rows[0]?.description||'The provider did not return a description.'}</p><p>Latest tokenized price: <strong>{money(value(rwaQuotes?.data?.rows?.[0],'average_tokenized_price'))}</strong></p><Evidence result={rwa}/><Evidence result={rwaQuotes}/><details><summary>Inspect returned instrument fields</summary><pre>{JSON.stringify(rwa.data.rows[0],null,2)}</pre></details></>:<p>Select a row to read its metadata and a separate market quote.</p>}<p className="caution">Redemption rights, custody, geographic availability and investor eligibility are not verified by a market quote.</p></section><section className="panel"><div className="eyebrow">ISSUER EVIDENCE</div><h2>Who issues the token?</h2>{(issuers?.data?.rows||[]).map(row=><button className="ledger-row" key={row.issuer_id} onClick={()=>run(async()=>setIssuer(await research('issuer',{issuer_id:row.issuer_id,limit:10})))}><strong>{row.name||row.issuer_name||row.issuer_id}</strong><span>Read issuer ↗</span></button>)}<Evidence result={issuers}/>{issuer&&<><p>{issuer.data.rows[0]?.description||'No issuer description returned.'}</p><details><summary>Inspect issuer fields</summary><pre>{JSON.stringify(issuer.data.rows[0],null,2)}</pre></details><Evidence result={issuer}/></>}<p className="fine">An issuer identifier is distinct from both a CMC crypto ID and an RWA ID.</p></section></div>
      </>}
      {tab==='structure'&&<><div className="page-title"><div><div className="eyebrow">MARKET STRUCTURE</div><h1>Market participation</h1><p>Compare venues, inspect derivatives and keep liquidation context separate from execution.</p></div></div><section className="panel"><div className="section-title"><h2>Derivatives venues</h2><span>Shared market snapshot</span></div><table><thead><tr><th>Venue</th><th>Open interest</th><th>24h derivatives volume</th></tr></thead><tbody>{(exchanges?.data?.rows||[]).map(row=><tr key={row.exchange_id}><td><strong>{row.exchange_name||row.name}</strong></td><td>{money(value(row,'open_interest'))}</td><td>{money(value(row,'derivative_volume','derivative_volume_usd','volume_24h'))}</td></tr>)}</tbody></table><Evidence result={exchanges}/></section><div className="below-grid"><section className="panel"><div className="section-title"><h2>Ethereum derivatives</h2><button className="secondary" onClick={()=>run(async()=>setPairs(await research('derivativePairs',{crypto_id:1027,limit:10})))}>Load pairs ↗</button></div>{(pairs?.data?.rows||[]).map((row,i)=><div className="fact-row" key={row.id||i}><strong>{row.market_pair||row.symbol||row.exchange_name||'Derivative pair'}</strong><span>Funding: {text(value(row,'funding_rate'))}</span><span>Open interest: {money(value(row,'open_interest'))}</span></div>)}<Evidence result={pairs}/><p className="fine">Funding conventions and instrument definitions differ. No inferred bid/ask or executable spread is shown.</p></section><section className="panel"><div className="section-title"><h2>Liquidation context</h2><button className="secondary" onClick={()=>run(async()=>setLiquidations(await research('liquidations')))}>Load summary ↗</button></div>{liquidations&&<><table><thead><tr><th>Period</th><th>Total (USD)</th><th>Long (USD)</th><th>Short (USD)</th></tr></thead><tbody>{liquidations.data.rows.map((row,i)=><tr key={i}><td>{text(row.time_period)}</td><td>{money(value(row,"total_liquidations"))}</td><td>{money(value(row,"long_liquidations"))}</td><td>{money(value(row,"short_liquidations"))}</td></tr>)}</tbody></table><details><summary>Inspect source fields</summary><pre>{JSON.stringify(liquidations.data.rows,null,2)}</pre></details></>}<Evidence result={liquidations}/><p className="caution">Aggregate liquidation evidence describes observed market conditions; it cannot determine your execution outcome.</p></section></div><section className="panel reflection"><h2>Turn observations into research.</h2><p>Return to the notebook and record the evidence that changed your view. Original notes stay attached to the time you saved them.</p><button className="primary" onClick={()=>{setTab('asset');setThesis('Review market structure and participation')}}>Open the notebook ↗</button></section>
      </>}
      <footer><span>INVESTOR INTEL / LOCAL EXTRACTION</span><span>{fixture?'Synthetic market evidence · No external calls':'Data provided by '} {!fixture&&<a href="https://coinmarketcap.com" target="_blank" rel="noreferrer">CoinMarketCap.com</a>}</span></footer>
      {details&&<div className="modal-backdrop" onClick={()=>setDetails(null)}><div className="modal intel-root" onClick={e=>e.stopPropagation()}><MarkerDetails events={[details]} onClose={()=>setDetails(null)} t={t}/></div></div>}
    </main>
  </div>
}
createRoot(document.getElementById('root')).render(<App/> )



