import React from 'react'
const time=value=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'long'}):'Not recorded'
export default function JournalMarkerReceipt({changes}){
 const condition=changes?.condition_receipt?.after,review=changes?.performance_evaluation?.after
 if(!condition&&!review)return null
 return <section aria-label="Original journal evidence" className="border-t border-[var(--border-default)] pt-2 space-y-2">
  {condition&&<><h4>Original condition evidence</h4><dl className="intel-event-facts"><dt>Evidence version</dt><dd>{condition.evidence_version}</dd><dt>Saved comparison</dt><dd>{condition.condition?.metric} {condition.condition?.comparator} {condition.condition?.threshold??'Not recorded'} {condition.condition?.threshold_unit} · {condition.condition?.time_window}</dd><dt>Source observation</dt><dd>{time(condition.observation?.observedAt)}</dd><dt>First known</dt><dd>{time(condition.observation?.recordedAt)}</dd><dt>Evaluated</dt><dd>{time(condition.checkedAt)}</dd><dt>Source</dt><dd className="break-all">{condition.observation?.sourceRef||'Unavailable'}</dd></dl>{(condition.observation?.sourceMetric||/^(venue|depth|liquidation):/.test(condition.condition?.source_metric||''))&&<p className="break-all">Matched source: {condition.observation?.sourceMetric||'Not recorded in this receipt'}</p>}<p>Recorded condition result: {condition.met===true?'met':condition.met===false?'not met':'unavailable'}. Your investment conclusion remains yours.</p></>}
  {review&&<><h4>Original performance assessment</h4><p>{review.assessment} · recorded {time(review.recorded_at)}</p><dl className="intel-event-facts"><dt>Original decision</dt><dd>{time(review.original_forecast?.occurred_at)}</dd><dt>Review window</dt><dd>{time(review.from)} — {time(review.to)}</dd><dt>Window declared</dt><dd>{time(review.window_declared_at)}</dd><dt>Fees</dt><dd>{review.fees_assumption}</dd><dt>Slippage</dt><dd>{review.slippage_assumption}</dd></dl><p>Research assessment, separate from realized portfolio and journal P&L.</p><details><summary>Assessment evidence references</summary><ul className="break-all">{(review.evidence_refs||[]).map((ref,index)=><li key={index}>{ref}</li>)}</ul></details></>}
 </section>
}
