import React,{useEffect,useRef,useState} from 'react'
import {Link} from 'react-router'
import {useTranslation} from 'react-i18next'
import {requestChartWorkspace} from '../lib/chart-workspace-api'
const date=value=>value?new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'long'}):'—'
const labels={queued:'Queued',sending:'Attempt in progress',provider_accepted:'Provider accepted',failed:'Failed',expired:'Expired',cancelled:'Cancelled',unknown:'Outcome unknown',retry:'Rate limited · retry scheduled'}
const stateLabel=(state,t)=>labels[state]?t(`alerts.delivery.states.${state}`,{defaultValue:labels[state]}):state
export default function AlertDelivery(props){return <Delivery key={`${props.context.userId}:${props.context.orgId}:${props.ruleId}`} {...props}/>}
function Delivery({ruleId,context}){
 const {t}=useTranslation('intel',{useSuspense:false})
 const [open,setOpen]=useState(false),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(null),[consent,setConsent]=useState(false),alive=useRef(true)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 const load=async(page=0)=>{setBusy(true);setError(null);try{const result=await requestChartWorkspace(context,{operation:'alert_delivery_status',id:ruleId,page});if(alive.current){setData(result);setConsent(result.enabled)}}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 const save=async()=>{setBusy(true);setError(null);try{await requestChartWorkspace(context,{operation:'alert_delivery_preference',id:ruleId,enabled:consent});if(alive.current)await load()}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 return <section aria-label={t('alerts.delivery.section_label',{defaultValue:'Delivery preferences and attempts'})}><button className="intel-text-link" aria-expanded={open} onClick={()=>{setOpen(!open);if(!open)load()}}>{t('alerts.delivery.toggle',{defaultValue:'Delivery & receipts'})}</button>{open&&<>
  {busy&&<p role="status">{t('alerts.delivery.loading',{defaultValue:'Loading delivery state…'})}</p>}{error&&<><p role="alert">{error}</p><button className="btn" onClick={()=>load()}>{t('alerts.delivery.retry_read',{defaultValue:'Retry delivery read'})}</button></>}
  {data&&<><p className="intel-analysis-caption">{t('alerts.delivery.in_app_note',{defaultValue:'In-app alerts stay in this workspace. Telegram acceptance does not confirm delivery or reading; marking an alert read is a separate action.'})}</p>
   {!data.workerEnabled&&<p role="status">{t('alerts.delivery.worker_disabled',{defaultValue:'External delivery is not enabled on the service. No message will be sent until release is authorized.'})}</p>}
   {data.linked?<><label className="intel-workstation-check"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)}/>{t('alerts.delivery.consent_label',{defaultValue:'Send future firings of this rule to my linked private Intel Telegram chat'})}</label><p className="intel-analysis-caption">{t('alerts.delivery.consent_scope',{defaultValue:'Includes the saved alert title, firing time and a private workspace link. Market data and trade notes stay in Investor Intel. Three attempts maximum; expires after 24 hours. You can opt out here or revoke the connection in Settings.'})}</p><button className="btn" disabled={busy||consent===data.enabled} onClick={save}>{t('alerts.delivery.save_preference',{defaultValue:'Save delivery preference'})}</button></>:<p>{t('alerts.delivery.telegram_unavailable',{defaultValue:'Private Telegram alerts are unavailable.'})} <Link to="/intel/settings" className="intel-text-link">{t('alerts.delivery.review_connection',{defaultValue:'Review your Intel Telegram connection'})}</Link></p>}
   {data.enabled&&<p>{t('alerts.delivery.consent_recorded',{date:date(data.consentAt),defaultValue:'Consent recorded {{date}}'})}</p>}
   {data.rows.length===0?<p>{t('alerts.delivery.no_records',{defaultValue:'No delivery records on this page. In-app firing history remains above.'})}</p>:<ol className="intel-study-list">{data.rows.map(row=><li key={row.id}><strong>{stateLabel(row.state,t)}</strong><time>{date(row.created_at)}</time><p>{t('alerts.delivery.channel_private_telegram',{defaultValue:'Private Telegram'})} · {t('alerts.delivery.attempts_total',{n:row.attempt_count,defaultValue:'{{n}} attempts'})} · {t('alerts.delivery.expires_at',{date:date(row.expires_at),defaultValue:'expires {{date}}'})}</p>{row.reason&&<p>{row.reason.replaceAll('_',' ')}</p>}<details><summary>{t('alerts.delivery.attempts_and_event',{defaultValue:'Attempts and source event'})}</summary><p className="break-all">{t('alerts.delivery.event',{defaultValue:'Event'})} {row.event_id}</p><ol>{[...(row.intel_alert_delivery_attempts||[])].sort((a,b)=>a.attempt-b.attempt).map(attempt=><li key={attempt.attempt}>{t('alerts.delivery.attempt_number',{n:attempt.attempt,defaultValue:'Attempt {{n}}'})} · {stateLabel(attempt.outcome,t)} · {date(attempt.started_at)}{attempt.http_status!=null?` · HTTP ${attempt.http_status}`:''}{attempt.provider_message_id?` · ${t('alerts.delivery.provider_reference',{defaultValue:'Provider reference'})} ${attempt.provider_message_id}`:''}</li>)}</ol></details></li>)}</ol>}
   {(data.hasOlder||data.page>0)&&<nav aria-label={t('alerts.delivery.pages_label',{defaultValue:'Delivery pages'})}><button disabled={busy||data.page===0} onClick={()=>load(data.page-1)}>{t('alerts.delivery.newer_attempts',{defaultValue:'Newer attempts'})}</button><span> {t('alerts.delivery.page_number',{n:data.page+1,defaultValue:'Page {{n}}'})} </span><button disabled={busy||!data.hasOlder} onClick={()=>load(data.page+1)}>{t('alerts.delivery.older_attempts',{defaultValue:'Older attempts'})}</button></nav>}
  </>}
 </>}</section>
}
