import React,{useEffect,useRef,useState} from 'react'
const time=t=>new Date(t).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'long'})
const utcInput=t=>new Date(t).toISOString().slice(0,-1)
const errors={chart_review_revision_conflict:'This note changed in another tab. Reload the review before editing.',chart_review_comment_deleted:'This note was deleted. A retry cannot restore it.',chart_review_anchor_outside_snapshot:'Choose a time inside the saved chart period.',chart_review_limit:'This review has reached 1,000 notes.',chart_review_unavailable:'Review access is unavailable. The link may have expired, been revoked or require a different account.'}
export async function requestChartReview(supabase,token,body) {
 const {data,error}=await supabase.functions.invoke('intel-chart-share',{body:{...body,token}})
 if(error){const details=await error.context?.json?.().catch(()=>null);throw new Error(errors[details?.error]||'The review could not be loaded or saved. Retry when the service is available.')}
 if(data?.error)throw new Error(errors[data.error]||'Review unavailable.')
 return data
}
export default function ChartReviewPanel(props){return <ReviewBody key={`${props.userId}:${props.token}`} {...props}/>}
function ReviewBody({supabase,token,snapshot,onSelect,onRows,observation}) {
 const [open,setOpen]=useState(false),[state,setState]=useState(null),[page,setPage]=useState(0),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(null),[retry,setRetry]=useState(0)
 const alive=useRef(true),sequence=useRef(0),operation=useRef(null),opener=useRef(null)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;sequence.current++}},[])
 const read=async()=>{
  const id=++sequence.current;setError(null)
  try{const result=await requestChartReview(supabase,token,{operation:'review_list',page});if(alive.current&&sequence.current===id){setState(result);onRows?.(result.rows)}}catch(e){if(alive.current&&sequence.current===id){setError(e.message);setState(null);onRows?.([])}}
 }
 useEffect(()=>{if(open)void read();else{sequence.current++;setForm(null);setState(null);onRows?.([])}},[open,page,retry]) // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!open)return;const visible=()=>{if(document.visibilityState==='visible'){setState(null);onRows?.([]);setRetry(r=>r+1)}};const timer=setInterval(()=>{if(document.visibilityState==='visible')setRetry(r=>r+1)},30000);document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visible)}},[open]) // eslint-disable-line react-hooks/exhaustive-deps
 const edit=row=>{const last=(snapshot.comparisonSeries?.[0]?.bars||snapshot.bars)?.at(-1),current=observation&&snapshot.layout.comparison?{t:observation.t,price:observation.prices[snapshot.layout.asset]??''}:null,anchor=row?.anchor||current||snapshot.layout.drawings[0]?.anchors[0]||{t:snapshot.layout.range.to,price:last?.c??''};setForm({id:row?.id??null,revision:row?.revision??0,text:row?.text||'',asset:anchor.asset||snapshot.layout.asset,at:utcInput(anchor.t),price:anchor.price});setError(null)}
 const changeAsset=asset=>setForm(f=>({...f,asset,price:observation?.t===Date.parse(f.at+'Z')?observation.prices[asset]??'':''}))
 const save=async e=>{
  e.preventDefault();const anchor={t:Date.parse(form.at+'Z'),price:Number(form.price),...(snapshot.layout.comparison?{asset:form.asset}: {})}
  if(!Number.isFinite(anchor.t)||anchor.t<snapshot.layout.range.from||anchor.t>snapshot.layout.range.to||!Number.isFinite(anchor.price)||anchor.price<=0){setError('Enter a positive price and a UTC time within this saved chart.');return}
  const body={operation:'review_save',id:form.id,revision:form.revision,text:form.text,anchor};const signature=JSON.stringify(body);if(operation.current?.signature!==signature)operation.current={signature,id:crypto.randomUUID()};setBusy(true);setError(null)
  try{await requestChartReview(supabase,token,{...body,operationId:operation.current.id});if(alive.current){operation.current=null;setForm(null);await read();opener.current?.focus()}}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}
 }
 const remove=async row=>{setBusy(true);setError(null);try{await requestChartReview(supabase,token,{operation:'review_delete',id:row.id,revision:row.revision});if(alive.current){if(form?.id===row.id)setForm(null);await read()}}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 return <section className="intel-chart-review"><button className="intel-text-link" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>Review this chart</button>{open&&<>
  <div className="intel-holdings-toolbar"><h2>{snapshot.audience==='org'?'Team review':'Private review'}</h2><button ref={opener} className="btn" disabled={busy} onClick={()=>edit(null)}>Add note</button></div><p className="intel-analysis-caption">Notes are visible to this {snapshot.audience==='org'?'organization':'owner-only'} link’s authorized readers. Each note has a chart anchor and a separate writing time.</p>
  {error&&<p role="alert">{error} <button className="intel-text-link" onClick={()=>setRetry(r=>r+1)}>Reload review</button></p>}
  {form&&<form className="intel-chart-review-form" onSubmit={save}><div className="intel-chart-alert-fields">{snapshot.layout.comparison&&<label>Anchor asset<select value={form.asset} disabled={busy} onChange={e=>changeAsset(e.target.value)}>{snapshot.layout.comparison.assets.map(a=><option value={a.asset} key={a.asset}>{a.label}</option>)}</select></label>}<label>Anchor time (UTC)<input type="datetime-local" step="0.001" required value={form.at} disabled={busy} onInput={e=>{const at=e.currentTarget.value;setForm(f=>({...f,at}))}} onChange={e=>setForm(f=>({...f,at:e.target.value}))}/></label><label>Anchor price ({snapshot.comparisonSeries?.find(s=>s.asset===form.asset)?.source.currency||snapshot.source.currency})<input type="number" min="0" step="any" required value={form.price} disabled={busy} onChange={e=>setForm(f=>({...f,price:e.target.value}))}/></label></div><label>Your review note<textarea maxLength={2000} rows={3} required value={form.text} disabled={busy} onChange={e=>setForm(f=>({...f,text:e.target.value}))}/></label><div className="intel-investigation-controls"><button className="btn btn--primary" type="submit" disabled={busy||!form.text.trim()}>{busy?'Saving…':form.id?'Save note changes':'Save review note'}</button><button className="btn" type="button" disabled={busy} onClick={()=>setForm(null)}>Cancel</button></div></form>}
  {!state&&!error?<p role="status">Loading review…</p>:state?.rows.length===0?<p>No notes in this page. Add a time and price reference to begin.</p>:<ol className="intel-chart-review-notes">{state?.rows.map(row=><li key={row.id}><div className="intel-holdings-toolbar"><strong>{row.author}</strong><span className="intel-analysis-caption">Written {time(row.createdAt)}{row.revision>1?` · edited ${time(row.updatedAt)} · revision ${row.revision}`:''}</span></div><button className="intel-text-link" onClick={()=>onSelect?.(row)}>Show anchor · {snapshot.layout.comparison&&`${snapshot.layout.comparison.assets.find(a=>a.asset===row.anchor.asset)?.label||'Asset unavailable'} · `}{time(row.anchor.t)} · {Number(row.anchor.price).toLocaleString(undefined,{maximumFractionDigits:8})} {snapshot.comparisonSeries?.find(s=>s.asset===row.anchor.asset)?.source.currency||snapshot.source.currency}</button><blockquote className="whitespace-pre-wrap break-words">{row.text}</blockquote><div className="intel-investigation-controls">{row.canEdit&&<button className="intel-text-link" disabled={busy} onClick={()=>edit(row)}>Edit note</button>}{row.canDelete&&<button className="intel-text-link" disabled={busy} onClick={()=>remove(row)}>Delete note</button>}</div></li>)}</ol>}
  {state&&<div className="intel-chart-navigation"><button className="btn" disabled={busy||page===0} onClick={()=>{setState(null);onRows?.([]);setPage(p=>p-1)}}>Previous notes</button><span>{state.rows.length} of {state.total} notes · page {page+1}</span><button className="btn" disabled={busy||!state.hasMore} onClick={()=>{setState(null);onRows?.([]);setPage(p=>p+1)}}>Next notes</button></div>}
 </>}</section>
}
