import React,{useEffect,useRef,useState} from 'react'
import {requestChartReview} from './ChartReviewPanel'
export default function ChartReviewCleanup({supabase,token}){
 const [open,setOpen]=useState(false),[state,setState]=useState(null),[page,setPage]=useState(0),[error,setError]=useState(null),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0)
 const alive=useRef(true),sequence=useRef(0)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;sequence.current++}},[])
 useEffect(()=>{if(!open)return;const request=++sequence.current;setState(null);setError(null);requestChartReview(supabase,token,{operation:'review_owned',page}).then(result=>{if(alive.current&&request===sequence.current)setState(result)},e=>{if(alive.current&&request===sequence.current)setError(e.message)});return()=>{sequence.current++}},[supabase,token,page,open,retry])
 const remove=async row=>{setBusy(true);setError(null);try{await requestChartReview(supabase,token,{operation:'review_delete',id:row.id,revision:row.revision});if(alive.current){if(state.rows.length===1&&page>0)setPage(p=>p-1);else setRetry(n=>n+1)}}catch(e){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 return <section className="intel-chart-review"><button className="intel-text-link" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>Manage my review notes</button>{open&&<><p className="intel-analysis-caption">You can delete your own notes while you remain a member of this workspace. This does not reopen the shared chart.</p>{error&&<p role="alert">{error} <button className="intel-text-link" onClick={()=>setRetry(n=>n+1)}>Retry notes</button></p>}{!state&&!error?<p role="status">Loading your notes…</p>:state?.rows.length===0?<p>No notes you authored remain on this link.</p>:<ol className="intel-chart-review-notes">{state?.rows.map(row=><li key={row.id}><span>Written {new Date(row.createdAt).toLocaleString()} · revision {row.revision}</span><blockquote className="whitespace-pre-wrap break-words">{row.text}</blockquote><button type="button" className="intel-text-link" disabled={busy} onClick={()=>remove(row)}>Delete my note</button></li>)}</ol>}{state&&<div className="intel-chart-navigation"><button type="button" disabled={busy||page===0} onClick={()=>setPage(p=>p-1)}>Previous notes</button><span>Page {page+1}</span><button type="button" disabled={busy||!state.hasMore} onClick={()=>setPage(p=>p+1)}>Next notes</button></div>}</>}</section>
}
