import React,{useEffect,useId,useRef,useState} from 'react'
import {useTranslation} from 'react-i18next'
import {requestChartWorkspace} from '../lib/chart-workspace-api'
import {chartShareUrl,chartShareShortUrl} from '../lib/chart-share-url'
import ChartShareCard from './ChartShareCard'
const AUDIENCES=[['owner','Only me'],['org','Current organization'],['unlisted','Anyone with the link'],['public','Public']]
const fullUrl=share=>chartShareUrl(share,window.location.origin,import.meta.env.VITE_INTEL_CHART_LINK_PREVIEW==='true')
function ChartShareControlsBody({context,snapshot,autoOpen=false}){
 const {t}=useTranslation('intel',{useSuspense:false})
 const drawings=snapshot.state?.layout?.drawings||[]
 // Every saved drawing travels with the link by default: a reader is meant to
 // see the chart the member made. Clearing one leaves that note behind.
 const [open,setOpen]=useState(autoOpen),[audience,setAudience]=useState('owner'),[days,setDays]=useState(7),[selected,setSelected]=useState(()=>drawings.map(d=>d.id)),[shares,setShares]=useState([]),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(null),[result,setResult]=useState(null),[copied,setCopied]=useState(false)
 const modal=useRef(null),trigger=useRef(null),operation=useRef(null),alive=useRef(true),generation=useRef(0),listing=useRef(0),heading=useId()
 const audienceName=value=>t(`chart.share.controls.audience_${value}`,{defaultValue:AUDIENCES.find(([key])=>key===value)?.[1]||value})
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 const refresh=async(next=0)=>{const current=generation.current,request=++listing.current;try{const r=await requestChartWorkspace(context,{operation:'share_list',snapshotId:snapshot.id,page:next});if(alive.current&&current===generation.current&&request===listing.current){setShares(r.shares||[]);setPage(next);setHasMore(!!r.hasMore)}}catch(e){if(alive.current&&current===generation.current&&request===listing.current)setError(e.message)}}
 useEffect(()=>{if(!open)return;modal.current?.showModal();refresh()},[open]) // eslint-disable-line
 const close=()=>{generation.current++;setBusy(false);setOpen(false);trigger.current?.focus()}
 const create=async()=>{
  const current=++generation.current
  const signature=JSON.stringify({audience,days,selected});if(operation.current?.signature!==signature)operation.current={signature,id:crypto.randomUUID(),expiresAt:Date.now()+days*86400000}
  setBusy(true);setError(null)
  try{const r=await requestChartWorkspace(context,{operation:'share_create',snapshotId:snapshot.id,operationId:operation.current.id,audience,expiresAt:operation.current.expiresAt,includeDrawingIds:selected});if(alive.current&&current===generation.current){setResult(r.share);operation.current=null;await refresh()}}
  catch(e){if(alive.current&&current===generation.current)setError(e.message)}finally{if(alive.current&&current===generation.current)setBusy(false)}
 }
 const revoke=async id=>{const current=++generation.current;setBusy(true);setError(null);try{await requestChartWorkspace(context,{operation:'share_revoke',id});if(alive.current&&current===generation.current){setResult(r=>r?.id===id?null:r);await refresh(page)}}catch(e){if(alive.current&&current===generation.current)setError(e.message)}finally{if(alive.current&&current===generation.current)setBusy(false)}}
 const short=result?chartShareShortUrl(result):'',long=result?fullUrl(result):''
 const primary=short||long
 const copy=async()=>{const current=generation.current;try{await navigator.clipboard.writeText(primary);if(alive.current&&current===generation.current)setCopied(true)}catch{if(alive.current&&current===generation.current)setError(t('chart.share.controls.copy_unavailable',{defaultValue:'Select and copy the link below. Clipboard access is unavailable.'}))}}
 return <><button className="intel-text-link" ref={trigger} type="button" onClick={()=>{setOpen(true);setResult(null);setCopied(false);setAudience('owner');setSelected(drawings.map(d=>d.id));setError(null)}}>{t('chart.share.controls.open',{defaultValue:'Share snapshot'})}</button>
 {open&&<dialog ref={modal} className="intel-chart-study-dialog" aria-labelledby={heading} onCancel={e=>{e.preventDefault();close()}}>
  <div className="intel-investigation-analysis-heading"><h2 id={heading}>{t('chart.share.controls.heading',{defaultValue:'Choose who can read this chart'})}</h2><button type="button" onClick={close}>{t('common.close',{defaultValue:'Close'})}</button></div>
  <p>{snapshot.title}</p><p className="intel-analysis-caption">{t('chart.share.controls.intro',{defaultValue:'The link opens this saved version, with the drawings and indicators you saved. A reader can zoom and read, and cannot change the chart. Clear a note below to leave it out.'})}</p>
  <ChartShareCard layout={snapshot.state?.layout} source={snapshot.state?.source} capturedAt={snapshot.state?.capturedAt} latestObservation={snapshot.state?.bars?.at(-1)?.t??null}/>
  <div className="intel-investigation-controls"><label>{t('chart.share.controls.audience',{defaultValue:'Audience'})}<select value={audience} disabled={busy||!!result} onChange={e=>setAudience(e.target.value)}>{AUDIENCES.map(([value])=><option key={value} value={value}>{audienceName(value)}</option>)}</select></label><label>{t('chart.share.controls.expiry',{defaultValue:'Link expires'})}<select value={days} disabled={busy||!!result} onChange={e=>setDays(Number(e.target.value))}><option value={1}>{t('chart.share.controls.expiry_1',{defaultValue:'In 1 day'})}</option><option value={7}>{t('chart.share.controls.expiry_7',{defaultValue:'In 7 days'})}</option><option value={30}>{t('chart.share.controls.expiry_30',{defaultValue:'In 30 days'})}</option></select></label></div>
  {audience==='org'&&<p className="intel-analysis-caption">{t('chart.share.controls.org_note',{defaultValue:'Readers must be current members of this organization with Investor Intel access.'})}</p>}
  {['unlisted','public'].includes(audience)&&<p className="intel-analysis-caption">{t('chart.share.controls.link_note',{defaultValue:'Anyone who receives this link can read the selected content. A reader can keep a copy. Revoking a link blocks later reads, but cannot erase copies.'})}</p>}
  {['unlisted','public'].includes(audience)&&import.meta.env.VITE_INTEL_CHART_LINK_PREVIEW==='true'&&<p className="intel-analysis-caption">{t('chart.share.controls.preview_note',{defaultValue:'Social previews show Investor Intel branding only. Your chart title, prices and selected notes appear after opening the chart.'})}</p>}
  <fieldset className="intel-snapshot-annotations"><legend>{t('chart.share.controls.annotations_legend',{defaultValue:'Notes and drawings to include'})}</legend>{drawings.map(d=><label key={d.id}><input type="checkbox" checked={selected.includes(d.id)} disabled={busy||!!result} onChange={e=>setSelected(ids=>e.target.checked?[...ids,d.id]:ids.filter(id=>id!==d.id))}/><span>{d.text||d.tool.replaceAll('_',' ')}</span></label>)}{drawings.length===0&&<p>{t('chart.share.controls.no_annotations',{defaultValue:'No annotations in this snapshot.'})}</p>}</fieldset>
  <p className="intel-analysis-caption">{t('chart.share.controls.exclusions',{defaultValue:'Portfolio holdings and trade history are excluded. Source permissions are checked before creating a link and when it is opened.'})}</p>
  {error&&<p role="alert">{error}</p>}{result?<div role="status"><label className="intel-research-field">{t('chart.share.controls.link_label',{defaultValue:'Your chart link'})}<input readOnly value={primary} onFocus={e=>e.target.select()}/></label><button type="button" onClick={copy}>{copied?t('chart.share.controls.copied',{defaultValue:'Link copied'}):t('chart.share.controls.copy',{defaultValue:'Copy link'})}</button>
   {short?<details className="intel-chart-readings"><summary>{t('chart.share.controls.full_address',{defaultValue:'Full address'})}</summary><p className="break-all">{long}</p></details>:<p className="intel-analysis-caption">{t('chart.share.controls.short_unavailable',{defaultValue:'A short address is not available for this link yet, so this is its full address.'})}</p>}
   <p>{t('chart.share.controls.expires_audience',{date:new Date(result.expires_at).toLocaleString(),audience:audienceName(result.audience||audience),defaultValue:'Expires {{date}} · {{audience}}'})}</p></div>:<button type="button" className="btn btn--primary" disabled={busy} onClick={create}>{busy?t('chart.share.controls.creating',{defaultValue:'Creating link…'}):t('chart.share.controls.create',{defaultValue:'Create chart link'})}</button>}
  {shares.length>0&&<section className="intel-investigation-analysis"><h3>{t('chart.share.controls.existing',{defaultValue:'Existing links'})}</h3><ul className="intel-study-list">{shares.map(s=><li key={s.id}><span>{audienceName(s.audience)} · {s.revoked_at?t('chart.share.controls.revoked',{defaultValue:'Revoked'}):Date.parse(s.expires_at)<=Date.now()?t('chart.share.controls.expired',{defaultValue:'Expired'}):t('chart.share.controls.expires_on',{date:new Date(s.expires_at).toLocaleDateString(),defaultValue:'Expires {{date}}'})}</span>{!s.revoked_at&&Date.parse(s.expires_at)>Date.now()&&<button type="button" disabled={busy} onClick={()=>revoke(s.id)}>{t('chart.share.controls.revoke',{defaultValue:'Revoke link'})}</button>}</li>)}</ul><div className="intel-investigation-pagination"><button type="button" disabled={busy||page===0} onClick={()=>refresh(page-1)}>{t('chart.share.controls.previous',{defaultValue:'Previous'})}</button><span>{t('chart.share.controls.page',{page:page+1,defaultValue:'Page {{page}}'})}</span><button type="button" disabled={busy||!hasMore} onClick={()=>refresh(page+1)}>{t('chart.share.controls.next',{defaultValue:'Next'})}</button></div></section>}
 </dialog>}</>
}

export default function ChartShareControls(props){return <ChartShareControlsBody key={`${props.context.userId}:${props.context.orgId}:${props.snapshot.id}`} {...props}/>}
