import React,{useEffect,useState} from 'react'
import {Link} from 'react-router'
import {useSupabase} from '../../lib/useSupabase'
import {useProfile} from '../../lib/profile-context'
import {usePortfolioSelection} from '../lib/PortfolioSelectionContext'
export default function NarrativeBookOverlap(){
 const {supabase,user}=useSupabase(),{org}=useProfile(),selection=usePortfolioSelection(),[state,setState]=useState({}),[attempt,setAttempt]=useState(0)
 const scope=`${user?.id}:${org?.id}:${selection.portfolioId}`
 useEffect(()=>{if(!selection.portfolioId||selection.loading)return;let alive=true;setState({scope,loading:true});supabase.rpc('portfolio_exposure',{p_portfolio_id:selection.portfolioId}).then(({data,error})=>{if(alive)setState({scope,data,error:error?.message||(!Array.isArray(data?.narrative_exposure)?'Narrative exposure could not be read.':null)})}).catch(e=>{if(alive)setState({scope,error:e.message})});return()=>{alive=false}},[supabase,scope,selection.loading,attempt])
 const current=state.scope===scope?state:{loading:true}
 return <section className="border-y border-[var(--border-default)] py-4 space-y-3" aria-label="Narratives in your book"><div className="flex gap-4 items-center flex-wrap"><h2>Narratives in your book</h2><label className="text-xs">Portfolio<select className="select ml-2" value={selection.portfolioId||''} disabled={selection.loading} onChange={e=>selection.selectPortfolio(e.target.value)}>{selection.portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>{selection.error||current.error?<p role="alert">{selection.error?.message||current.error} <button className="intel-text-link" onClick={()=>setAttempt(n=>n+1)}>Retry</button></p>:!selection.portfolioId&&!selection.loading?<p>Choose a portfolio to see its exposure.</p>:current.loading?<p role="status">Loading narrative exposure…</p>:<><p className="text-xs text-[var(--fg-4)]">Up to eight largest matched narrative exposures in the selected portfolio. Associations may overlap and span issuer networks; these are not allocations to a network or a target portfolio.</p>{current.data.narrative_exposure.length?<div className="intel-table-scroll"><table aria-label="Narrative book overlap"><thead><tr><th>Narrative</th><th>Associated holdings</th><th>Share of book</th></tr></thead><tbody>{current.data.narrative_exposure.map(n=><tr key={n.slug}><th scope="row"><Link className="intel-text-link" to={`/intel/narratives/${n.slug}`}>{n.name}</Link></th><td>{Array.isArray(n.holdings)?n.holdings.join(', '):'Unavailable'}</td><td>{n.pct_of_book==null?'—':`${n.pct_of_book}%`}</td></tr>)}</tbody></table></div>:<p>No narrative matches in the current portfolio summary.</p>}{current.data.identity_coverage?.unmapped_research_holdings>0&&<p className="text-xs">{current.data.identity_coverage.unmapped_research_holdings} holdings have no verified research identity. Their value remains in the book.</p>}</>}</section>
}
