import { comparisonThreadHref } from '../lib/comparison-thread-link'
import React, { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router'
import { useTranslation } from 'react-i18next'
import { useWorkspacePreference } from '../context/PersonalWorkspace'
const time = value => new Date(value).toLocaleString(undefined, { timeZoneName: 'short' })

export default function ResearchThreadPanel({ subject, title, thread, onQuestion, onDecision, onRecord, onFlush }) {
  const { t } = useTranslation('intel', { useSuspense: false }), prefs = useWorkspacePreference('selection')
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(null), [confirmDelete, setConfirmDelete] = useState(false)
  const pane = useRef(null), opener = useRef(null), record = thread.record
  useEffect(() => { if (open) { pane.current?.showModal(); void thread.store.history(subject).catch(e => setError(e.message)) } }, [open, subject, thread.store])
  if (!record) return null
  const action = async fn => { setBusy(true); setError(null); try { await fn() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  const close = () => { pane.current?.close(); setOpen(false); setConfirmDelete(false); opener.current?.focus() }
  const pin = () => action(async () => { const saved = await onFlush(); if (!saved) throw Error('Write a question before pinning a thread.'); await prefs.save({ pinnedThreadId: saved.id }) })
  return <section className="intel-research-thread border-y border-[var(--border-default)] py-3 space-y-2" aria-label={t('thread.title', { defaultValue: 'Continuous investigation' })}>
    <div className="flex gap-3 items-end flex-wrap"><label className="flex-1 min-w-56"><span className="block text-xs text-[var(--fg-4)]">{t('thread.question', { defaultValue: 'Investigation question' })}</span><input className="input w-full" value={record.question} onChange={e => onQuestion(e.target.value)} maxLength={8000} placeholder={t('thread.question_hint', { defaultValue: 'What changed, and why does it matter?' })}/></label><button className="btn btn--quiet btn--sm" disabled={busy || record.loading || !record.question.trim()} onClick={() => action(() => onRecord('question'))}>{t('thread.record', { defaultValue: 'Record question' })}</button><button className="btn btn--quiet btn--sm" disabled={busy || prefs.loading || !!prefs.error} onClick={pin}>{record.thread?.id && prefs.value.pinnedThreadId === record.thread.id ? t('thread.pinned', { defaultValue: 'Thread pinned' }) : t('thread.pin', { defaultValue: 'Pin thread' })}</button><button className="btn btn--quiet btn--sm" ref={opener} onClick={() => setOpen(true)}>{t('thread.inspect', { defaultValue: 'Notes & history' })}</button></div>
    <p className="text-xs text-[var(--fg-4)]" role="status">{record.loading ? 'Loading your thread…' : record.saving ? 'Saving draft…' : record.error ? 'Draft not saved' : record.dirty ? 'Draft changes pending' : record.thread ? `Private draft saved · revision ${record.thread.revision}` : 'Private draft · recorded questions and receipts keep their original words.'}</p>
    {(error || record.error || prefs.error) && <p role="alert">{error || record.error || prefs.error}</p>}
    {open && <dialog ref={pane} className="intel-thread-inspector intel-investigation" aria-label="Investigation notes and history" onCancel={e => { e.preventDefault(); close() }}><header className="flex items-start justify-between gap-4"><div><p className="eyebrow">Continuous investigation</p><h2>{title}</h2><p className="text-xs break-all">Thread context · {subject}</p></div><button className="btn btn--quiet" onClick={close}>Close</button></header><label className="block my-4"><span>{t('thread.notes', { defaultValue: 'Your decision or notes' })}</span><textarea className="textarea w-full" rows={4} value={record.decision} maxLength={16000} onChange={e => onDecision(e.target.value)}/></label><div className="flex gap-3 flex-wrap"><button className="btn btn--primary" disabled={busy || !record.question.trim()} onClick={() => action(() => onRecord('note'))}>Record notes</button><Link className="btn btn--quiet" to={`/intel/compare?thread=${record.thread?.id || ''}`}>Compare assets</Link><button className="btn btn--quiet" disabled={busy} onClick={() => setConfirmDelete(true)}>Delete thread</button></div>
      {(error || record.error) && <p role="alert">{error || record.error}</p>}
      {confirmDelete && <div className="border-y py-3 my-3"><p>Delete this private draft and thread entries? Independently saved research receipts remain in Saved Research.</p><button className="btn btn--quiet" onClick={() => action(async () => { await thread.store.remove(subject); if (prefs.value.pinnedThreadId === record.thread?.id) await prefs.save({ pinnedThreadId: null }); close() })}>Confirm delete thread</button><button className="btn btn--quiet" onClick={() => setConfirmDelete(false)}>Keep thread</button></div>}
      {record.error && <details className="my-3"><summary>Resolve a save conflict</summary><p>Reloading replaces the visible draft with the server version. Copy any unsaved text you want to retain first.</p><button className="btn btn--quiet" onClick={() => action(() => thread.store.load(subject, true))}>Reload saved thread</button></details>}
      <h3 className="mt-5 mb-3">Recorded history</h3>{record.historyLoading ? <p role="status">Loading recorded history…</p> : record.historyError ? <p role="alert">{record.historyError}</p> : !record.entries.length && <p>No recorded entries yet. Drafts are separate from recorded decisions.</p>}<ol className="space-y-4">{record.entries.map(entry => <li key={entry.id} className="border-t pt-3"><p className="text-xs text-[var(--fg-4)]"><time dateTime={entry.recorded_at}>{time(entry.recorded_at)}</time> · {entry.action} · {entry.context?.lens || 'Research'}</p><h4 className="mt-1 whitespace-pre-wrap">{entry.question}</h4><p className="whitespace-pre-wrap">{entry.decision}</p>{entry.evidence_version && <p className="text-xs break-all">Evidence version: {entry.evidence_version}</p>}{comparisonThreadHref(record.thread?.id,entry.context?.comparison) && <Link className="intel-text-link block" to={comparisonThreadHref(record.thread?.id,entry.context.comparison)}>Resume recorded comparison</Link>}{entry.saved_research_id && <Link className="intel-text-link" to={`/intel/research?research_id=${entry.saved_research_id}`}>Open original saved research</Link>}{entry.context?.at != null && <p className="text-xs">Evidence cursor: {time(entry.context.at)}</p>}</li>)}</ol>{record.hasMore && <button disabled={record.historyLoading} className="btn btn--quiet" onClick={() => action(() => thread.store.history(subject, true))}>Older entries</button>}
    {record.page > 0 && <button className="btn btn--quiet" onClick={() => action(() => thread.store.history(subject))}>Newest entries</button>}
    </dialog>}
  </section>
}
